### ISSUE TITLE
Unable to open published post, edit and then republish

### ISSUE THREAD

**Issue by dnershi** [OpenLiveWriter/OpenLiveWriter#254] opened 2015-12-28 21:51 UTC
I published a post. I can retrieve it via open recent post. But when I try to make corrections and republish, I get an unexpected error: GoogleApiException.

Any insight is appreciated.

Dave

The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
We're sorry, but the value for field labels was not valid. [400]
Errors [
	Message[We're sorry, but the value for field labels was not valid.] Location[ - ] Reason[invalid] Domain[global]
]

   at Google.Apis.Requests.ClientServiceRequest`1.Execute()
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.EditPost(String blogId, BlogPost post, INewCategoryContext newCategoryContext, Boolean publish, String& etag, XmlDocument& remotePost)
   at OpenLiveWriter.BlogClient.Blog.EditPost(BlogPost post, INewCategoryContext newCategoryContext, Boolean publish)
   at OpenLiveWriter.PostEditor.UpdateWeblogAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by ScottIsAFool** [comment] 2015-12-28 22:19
Thanks for raising this, we are aware of the issue and looking to put in a fix. Dupe of #186

**Closed by ScottIsAFool** 2015-12-28 22:19 UTC

**Comment by dnershi** [comment] 2015-12-29 15:44
Thanks for your prompt response. I'll follow issue #186.

Cheers.

Dave
