### ISSUE TITLE
Open post System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by jtbworld** [OpenLiveWriter/OpenLiveWriter#226] opened 2015-12-23 03:58 UTC
Issue with 0.5.1.3 when I try to open a recently created post.

System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, IEnumerable`1 values)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.ConvertToBlogPost(Post post)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.<>c.<GetRecentPosts>b__38_0(Post p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetRecentPosts(String blogId, Int32 maxPosts, Boolean includeCategories, Nullable`1 now)
   at OpenLiveWriter.BlogClient.Blog.GetRecentPosts(Int32 maxPosts, Boolean includeCategories)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPosts(RecentPostRequest request, Boolean getPages)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetRecentPosts(RecentPostRequest request)
   at OpenLiveWriter.PostEditor.OpenPost.BlogPostListBox.GetRecentPostsAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by ScottIsAFool** [comment] 2015-12-23 07:36
Thanks for reporting this, it will be fixed in the next release. Dupe of #221

**Closed by ScottIsAFool** 2015-12-23 07:36 UTC
