### ISSUE TITLE
Thousands of build errors on when building in Visual Studio

### ISSUE THREAD

**Issue by WouterDeKort** [OpenLiveWriter/OpenLiveWriter#72] opened 2015-12-10 11:41 UTC
After cloning the repository, opening the solution and building it I get somewhere around 12.000 errors. All are related to projects not being able to find references to other projects.

After changing all the build output directories to bin\debug the project compiles without problems (except for some obsolete errors).

Running build.cmd succeeds without errors.

Is this something on my machine only? Any ideas?

**Comment by hmemcpy** [comment] 2015-12-10 11:59
You shouldn't change the output directory, but it probably needs to restore the NuGet packages first.
Try running `build.cmd` from the command line before opening the solution.

**Comment by WouterDeKort** [comment] 2015-12-10 12:05
I know I shouldn't change the output directory.  That's why I created an issue.

I've already ran build.cmd and that succeeds. All Nuget packages are restored.

The errors are about missing the OpenLiveWriter namespaces between projects.



On Thu, Dec 10, 2015 at 3:59 AM -0800, "Igal Tabachnik" <notifications@github.com<mailto:notifications@github.com>> wrote:


You shouldn't change the output directory, but it probably needs to restore the NuGet packages first.
Try running build.cmd from the command line before opening the solution.

-

**Comment by martinwoodward** [comment] 2015-12-10 13:00
What version of Visual Studio are you using?  With a fresh install of Visual Studio Community 2015 it builds cleanly for me

**Comment by WouterDeKort** [comment] 2015-12-10 13:01
Visual Studio 2015.1 Enterprise

**Comment by jonbgallant** [comment] 2015-12-10 14:11
I just did a fresh clone and was able to build without issue using 2015 Enterprise.  Can you include a couple of the errors you are getting?

**Comment by istudormarius** [comment] 2015-12-10 14:34
Hello, 
I think i have the same problem like WouterDeKort. 
I just opened the solution using Visual Studio 2015 Community Edition. I restored the Nuget Packages and i also ran build.cmd and i get a lot of errors. 
Here how it looks like:

![writererrors](https://cloud.githubusercontent.com/assets/6017029/11717893/7574a15e-9f53-11e5-978f-bc5f2e070467.JPG)

**Comment by timheuer** [comment] 2015-12-10 14:50
Can someone paste the project that is not building.  The errors are a ton because one project failed to build.  Look at the Output spew instead and you should be able to see early on likely the project that failed.  I initially hit this as well, but when I do a "Rebuild Solution" on the overall solution folder this is resolved.

**Comment by istudormarius** [comment] 2015-12-10 15:02
The project that is not building is OpenLiveWriter.Ribbon.
I see there is a thread open on this error.

1>------ Build started: Project: OpenLiveWriter.Ribbon, Configuration: Debug Win32 ------
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(203,5): error MSB3073: The command "UICC.exe Ribbon.xml Ribbon.bin /header:RibbonID.h /res:Ribbon.rc /name:Ribbon
1>C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(203,5): error MSB3073: :VCEnd" exited with code -1073741511.
1>OpenLiveWriter.Ribbon.rc(11): fatal error RC1015: cannot open include file 'RibbonID.h'.
1>

**Comment by timheuer** [comment] 2015-12-10 15:51
@istudormarius if you attempt to build that project (Rebuild Project) on its own first, does it still produce that error?

**Comment by timheuer** [comment] 2015-12-10 15:52
Closing as dupe of #69 now that we have these details.

**Closed by timheuer** 2015-12-10 15:52 UTC
