### ISSUE TITLE
Spelling don't work (with Russian lang)

### ISSUE THREAD

**Issue by n0tb0dy** [OpenLiveWriter/OpenLiveWriter#160] opened 2015-12-17 14:43 UTC
I don't know whether the work spelling with the English language, but with Russian language it does not work. WLW worked with the Russian language well.

**Comment by kathweaver** [comment] 2015-12-17 14:50
This is a duplicate of #130 

Spell check doesn't work for any language.

**Closed** 2015-12-17 14:57 UTC
