### ISSUE TITLE
Error code 500

### ISSUE THREAD

**Issue by farsideoffifty** [OpenLiveWriter/OpenLiveWriter#709] opened 2018-01-23 04:09 UTC
Windows 7  Cannot publish blog post I get the error code 500 
I went to my Google Photos and opened a new album and shared it.  Still no luck. 
The remote server returned an error: (500) Internal Server Error.
Please help

**Comment by syntasium** [comment] 2018-01-23 06:37
sama problem with windows 10 too

**Comment by MickeytheKid** [comment] 2018-01-23 08:29
I have the same problem with Windows 10.

**Comment by tubbystar** [comment] 2018-01-23 09:57
Yes, just had this this morning for the first time.

**Comment by yuanlin** [comment] 2018-01-23 10:48
same problem with win 10

**Comment by notinjersey** [comment] 2018-01-23 14:50
Same issue as of this morning. Help?!

**Comment by toobob** [comment] 2018-01-23 15:28
same issue here. i found that i CANNOT publish to blogger when inserting an image "from my computer" but CAN publish when inserting an image "from the web"
just started this morning

**Comment by vacationdreamer** [comment] 2018-01-23 16:16
Add me to the list.  :)
Was ok yesterday for me (1/22) but presented itself today.
Thank you for all your help!!!!  This group is such a blessing to me!

**Comment by JimGalasyn** [comment] 2018-01-23 18:21
Same problem on Windows 10 v1709 build 16299.192.

**Comment by crpaiva** [comment] 2018-01-23 18:41
This problem originates from Google Photos, which limits each album in 2000 photos. OLW can not open new album to continue posting photos from the computer. That is why photos from the WEB are posted without problem. I already read and tested a solution that consisted of opening a new album in Goole Photos with the same name as the other "Open Live Writer" and upload a photo to start. Leave the album public and you're done. This is the solution. It happens that I am trying and is not solving this time. Something's missing!!!

**Comment by notinjersey** [comment] 2018-01-23 18:55
Correct. My albums aren't full and I started a new one anyway but it still didn't help.

**Comment by crpaiva** [comment] 2018-01-23 18:56
I solved, temporarily, creating a new album "Open Live Writer" and uploading the photos that I want to post, within the article written in OLW. After uploading, I get the web addresses of the photos and change the ones I had originally linked to the computer. I published it and all right. But this is not the correct solution. I'm still researching the solution I used when I reached the 2000 photo limit in the OLW album in Google Photos.

**Comment by farsideoffifty** [comment] 2018-01-23 19:45
Is anyone out there working on a solution?  I have tried everything I can think of.  It is most certainly a OLW to Google Photos problem.  I contacted Google photos and they were no help at all 
I hope the Gurus here will have a solution soon   Thank you

**Comment by SteveP-UK** [comment] 2018-01-23 20:55
Me too! Windows 10. Never experienced this before. 20.00, UK time.

**Comment by Meldaron** [comment] 2018-01-23 23:40
Same issue today!

**Comment by debdeege** [comment] 2018-01-23 23:53
Same issue on Windows 10

**Comment by legalese22** [comment] 2018-01-24 05:59
Same here

**Comment by Rob2540** [comment] 2018-01-24 07:13
same issue. started yesterday..stressing

**Comment by bkford1** [comment] 2018-01-24 13:33
Same here. Windows 10.

**Comment by crpaiva** [comment] 2018-01-24 15:09
This problem is not related to the Operating System. This is a limitation of 2000 photos that Google Photos presents and that OLW is not able to handle. There is a way out but for now I suggest that you edit your article normally and before uploading, upload the photos to the Google Photos album in public condition and exchange the links to WEB link in OLW before publishing. Still searching.

**Comment by ScottIsAFool** [comment] 2018-01-24 15:14
Those who are having issues, have you tried following these steps? http://openlivewriter.org/tutorials/googlePhotoFix.html

**Comment by notinjersey** [comment] 2018-01-24 15:16
This time the problem is not the 2000 limit. My album is not full and I also created a new one but it did not help.

**Comment by crpaiva** [comment] 2018-01-24 15:26
The solution at http://openlivewriter.org/tutorials/googlePhotoFix.html is no longer solving the problem.
I've tested it twice without success. In the last instance this resolved. Not anymore. And there are people saying that you do not even have the album full.

**Comment by SteveP-UK** [comment] 2018-01-24 15:46
It doesn't work for me either Scott. I'm on Win 10 latest public release and 0.6.2.0 of OLW

**Comment by debdeege** [comment] 2018-01-24 16:01
I've tried that workaround Scott. It no longer works for me.

**Comment by banders03** [comment] 2018-01-24 18:53
I just encountered the problem, tried the fix and it didn't work.

**Comment by Rob2540** [comment] 2018-01-25 00:13
I Also tried the fix..it does not work for me.

**Comment by dnershi** [comment] 2018-01-25 14:13
Please note that Issues 709, 710, 711, 713 and 714 all relate to this same issue.

**Comment by JoniWebb** [comment] 2018-01-25 14:32
I freaked out after reading these messaged, so I just tested my blog and it published fine - I store my photos on Google photos.  I tested the new entry with two photos from two different folders saved on Photos.

Just wanted y'all to know that my blog, at least, is working fine - so it must not be a total glitch????  I hope!!!!

**Comment by dnershi** [comment] 2018-01-25 14:49
Hey Joni - It appears this problem has been resolved! Thanks OLW & Google!

**Comment by JoniWebb** [comment] 2018-01-25 14:51
Thank God!  I think I would implode if my OLW quit working.  Seriously.   It's the best blogging platform.

**Comment by notinjersey** [comment] 2018-01-25 14:56
The problem occurs when trying to publish photos through olw. Not when there are no photos or you are linking to them elsewhere.

**Comment by farsideoffifty** [comment] 2018-01-25 15:50
Yeah!!  Thank you to whoever solved the issue.  I was able to post to one of my blogs this morning.  Thank you again!  OLW is the best blogging platform ever and I was miserable without it.

**Comment by debdeege** [comment] 2018-01-25 15:53
Seems to be working fine now - publishing with pictures from OLW.  Thank you!

**Comment by crpaiva** [comment] 2018-01-25 16:07
I just posted an article through OLW and everything happened normally. It
seems to me that the creation of the new album, which I did yesterday, was
understood by OLW today. The photos went straight from my computer to the
album. It seems to me that we are OK again. Let's wait for the limit of
2000 photos in this album and see if OLW can create a new album by itself.

[ ]´s
Carlos Roberto e Gleidys
www.nasestradasdoplaneta.com.br
www.cozinhapraticanasestradas.com.br
www.turislogia.com.br


2018-01-25 12:56 GMT-02:00 notinjersey <notifications@github.com>:

**Comment by banders03** [comment] 2018-01-25 16:08
Working fine for me now, too!! Thank you to whoever fixed it! Also thanks to crpaiva for the suggested work around. I used it once and it worked great,

**Comment by bkford1** [comment] 2018-01-25 17:22
Works again! Thank you!

**Comment by tubbystar** [comment] 2018-01-25 19:27
Working again. Fantastic. Big hugs and thanks to whoever fixed it!

**Comment by Veshengro** [comment] 2018-01-25 19:41
It appears to have been a Google Photos issue

**Comment by banders03** [comment] 2018-01-25 22:43
I spoke too soon! The post publishes with photos but now I can't add a linking gadget to my post--it shows up as a broken image.  This is a script that I generate from another site and is a deal breaker for me. I have to use it. If you click on that broken image it takes you to the site where I generate the list but that's useless to viewers since I have to log in to see it. This is worse than the photos for me--I could at least use the workaround and add my linky tool. Now I can't add that. Help please!

**Comment by comstech23** [comment] 2018-01-25 22:47
Yay! It finally works!! Thank you so much!

**Comment by anserq** [comment] 2018-01-25 22:54
Do any of you here know why when I publish a post, it does not send me an email?
I noticed in blogger.
When I am on the blogger site, it uses a different username to publish it.
How can I make it the same for open live writer?

Is that the problem?

**Comment by Rob2540** [comment] 2018-01-26 00:41
Working now...many, many thanks you to whoever resolved this problem...

**Comment by Meldaron** [comment] 2018-01-26 07:14
Works for me again too, thanks!!!

**Comment by asiliuk5** [comment] 2019-02-09 10:44
I'm still getting the error... :(

**Comment by nvella** [comment] 2019-07-07 05:37
Hi,

As of PR #810 images now upload to Google Drive, as Google has completely removed the ability for third-party apps to upload images to Blogger, and images uploaded to Google Photos cannot be programmatically embedded. I'll close this issue for now, as the fix is currently in the developer builds and should be making it's way out to users in the next release. Please don't hesitate to get back in touch if you have any further questions. 👍 Cheers

**Closed by nvella** 2019-07-07 05:37 UTC
