### ISSUE TITLE
Opening Recent Post Gets Unexpected Error Argument Null Exception

### ISSUE THREAD

**Issue by dnershi** [OpenLiveWriter/OpenLiveWriter#232] opened 2015-12-23 15:39 UTC
I often schedule a post and then the next day, from a different computer, open a recent post to make any touchups needed. I currently cannot open a recent post.

I get an Unexpected Error - Argument Null Exception. Thanks for any help.

System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, IEnumerable`1 values)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.ConvertToBlogPost(Post post)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.<>c.<GetRecentPosts>b__38_0(Post p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetRecentPosts(String blogId, Int32 maxPosts, Boolean includeCategories, Nullable`1 now)
   at OpenLiveWriter.BlogClient.Blog.GetRecentPosts(Int32 maxPosts, Boolean includeCategories)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPosts(RecentPostRequest request, Boolean getPages)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetRecentPosts(RecentPostRequest request)
   at OpenLiveWriter.PostEditor.OpenPost.BlogPostListBox.GetRecentPostsAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by ScottIsAFool** [comment] 2015-12-23 15:41
Hi, thanks for reporting this, there is a fix been put in that will make its way to you with the next update. Dupe of #221

**Closed by ScottIsAFool** 2015-12-23 15:41 UTC

**Comment by dnershi** [comment] 2015-12-23 15:52
Gracias, Scott. Sorry for the duplication. Enjoying being able to use Live Writer again.

**Comment by martinwoodward** [comment] 2015-12-23 19:53
@dnershi - do you want to try downloading the latest build (0.5.1.4) from http://openlivewriter.org and see if that fixes the issue?  Thanks.

**Comment by dnershi** [comment] 2015-12-23 19:55
Will do, Martin.  David A. Nershi, PublisherToledo Wines and Vines Keeping you in touch with the area wine scene.28729 Simmons Road, Perrysburg, OH  43551 Phone: 419.351.0513     Member – International Food, Wine & Travel Writers Association 

    On Wednesday, December 23, 2015 2:53 PM, Martin Woodward <notifications@github.com> wrote:
 

 @dnershi - do you want to try downloading the latest build (0.5.1.4) from http://openlivewriter.org and see if that fixes the issue? Thanks.—

**Comment by dnershi** [comment] 2015-12-23 19:57
Martin - Yes, this has fixed the problem. Kudos to the OLW team and thanks!

**Comment by martinwoodward** [comment] 2015-12-23 19:59
You bet - thanks for the quick confirmation
