### ISSUE TITLE
"Correct" username and password invalid...

### ISSUE THREAD

**Issue by ezbiker** [OpenLiveWriter/OpenLiveWriter#108] opened 2015-12-12 16:57 UTC
Hello, I attempted to start setting up my blog with OLW; but in the config process I get an error box stating invalid username or password. I have used the same username and password for many years. Can you please help in resolving this? I have other blog accts. to setup as well!

![screenshott190](https://cloud.githubusercontent.com/assets/16262330/11763011/6e307178-a0c7-11e5-86ab-969d592258c2.png)

**Comment by kathweaver** [comment] 2015-12-12 17:00
Which blog host?  There is already an issue opened for Blogger.

**Comment by ezbiker** [comment] 2015-12-12 17:05
Same, Blogger.

**Comment by kathweaver** [comment] 2015-12-12 17:07
This is a duplicate of #63 so can be closed.

**Comment by willduff** [comment] 2015-12-12 17:17
I am working on a fix for this in pull request #101. Closing as a duplicate. Thanks!

**Closed by willduff** 2015-12-12 17:17 UTC
