### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by phatcher** [OpenLiveWriter/OpenLiveWriter#726] opened 2018-03-18 22:38 UTC
The last commit was 3 months ago and there's a bunch of open pull requests - is anyone maintaining this anymore?

**Comment by martingbrown** [comment] 2018-03-19 08:12
I was thinking the same thing.

**Comment by toobob** [comment] 2018-03-25 16:31
doesn't look like anybody's working on anything anymore. sad

**Comment by mguinness** [comment] 2018-04-03 17:00
I think part of the problem is that there is no roadmap for the product.  The contributors are all volunteers which means the only time they get to work on it is in their spare time which is in short supply for many.

Most likely someone would need to act as project manager to manage the issues and to corral the devs to work on bugs/enhancements.

Part of the problem is that issues have become a dumping ground for problems and aren't getting closed by the OP when issues are resolved which doesn't help.

**Comment by phatcher** [comment] 2018-04-09 10:15
I think @mguinness idea of a roadmap would be useful as I don't mind contributing but it would be nice to have an overall direction and apply some of the patches such as code highlighting.

**Comment by SvenVandenbrande** [comment] 2018-04-09 11:04
I agree, I also don't have a problem to contribute. But we need a direction. :) 
But you will see some reactions from Jon in the future. :)

**Comment by mguinness** [comment] 2018-04-09 18:58
Glad to hear the news, and from Jon no less.  I think an area where people can help is issue triage.  Maybe people can handle WordPress related issues, another Blogger etc. where they are knowledge on the platform.  Request to become a collaborator so you can close issues (over 400 open right now).

Also there are seven PR's from 2015.  I seriously doubt they'll be merged now so they should be closed and resubmitted if needed.  If issues and PR's are being addressed then that will go a long way to dispelling the abandonware label.

The one enhancement that could be worked on is plugins as the [gallery](http://openlivewriter.org/plugins/) is empty.  I think if that can be rectified that would be [popular](https://github.com/OpenLiveWriter/OpenLiveWriter/issues/19).

**Comment by kathweaver** [comment] 2018-04-09 20:29
I might be back too.  I got discouraged when I couldn't compile the code to fix accessibility issues, and I've been off earning some money.

**Comment by phatcher** [comment] 2018-04-12 19:37
@kathweaver if you have any spare let me know ;-)

**Comment by jongalloway** [comment] 2018-04-12 20:49
Hey, folks, thanks for all the interest. No, the project isn't dead, the main contributors just have all been pretty busy. I'm planning to get a release out in May or June. I'm really busy until the Build conference (May 7-9), and we'll also want to see if there are any obvious Windows app features that become available at Build.

My current plan is to start by reviewing open pull requests, so the best way for anyone to help is to test open pull requests and comment on the pull request with your results.

If you have more time, two open pull requests that need more input are #596 and #658:
 * #658 (Allow to add Code Snippets With Syntax Highlighting support) is working but would be great to get some testing and input if it's ready to ship
 * #596 (Add APPX Packaging Support) would really help us get automated builds going. Right now we have the traditional (MSI/Squirrel) build fully automated, but the APPX build is still manual. Fixing that would allow us to push out more regular builds. If you have expertise on this, or the time to study up on it, let me know. I've got some notes on what needs to happen. Right now we have a pull request, but it doesn't build. Maybe it's as simple as troubleshooting the PR build break?

I'm going to close this issue to encourage people to file separate specific issues on features or problems you're having rather than general project health discussion.

**Closed by jongalloway** 2018-04-12 20:49 UTC
