### ISSUE TITLE
New install: OLW Crashes when signing into blogger account

### ISSUE THREAD

**Issue by rgssolutions** [OpenLiveWriter/OpenLiveWriter#269] opened 2016-01-01 14:02 UTC
Just DL OLW for first time but have got nowhere as every time it starts DL of my selected blog it crashes and closes.

**Comment by ScottIsAFool** [comment] 2016-01-01 14:03
Can you post your log file please, at %localappdata%\openlivewriter

**Comment by rgssolutions** [comment] 2016-01-01 14:04
[Open Live Writer - Copy.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/75913/Open.Live.Writer.-.Copy.txt)

This one?

**Comment by ScottIsAFool** [comment] 2016-01-01 14:05
That's the one, thanks.

**Comment by ScottIsAFool** [comment] 2016-01-01 14:07
Ok, looks like this is a dupe of #267. Please follow that issue for progress on this.

**Closed by ScottIsAFool** 2016-01-01 14:07 UTC

**Comment by rgssolutions** [comment] 2016-01-01 14:08
Oh but that's still unresolved :( Is this going to take a while?

**Comment by ScottIsAFool** [comment] 2016-01-01 14:09
Hopefully not. When you try adding your blog, does it ask you if you want it to download supporting files for your theme? If it does, click no. That should (I think) at least let you use the application.

**Comment by rgssolutions** [comment] 2016-01-01 14:13
Nope all just runs auto

**Comment by mannrw** [comment] 2016-01-10 06:32
Thanks for addressing this issue my bloggger theme can now be updated with no issues.
