### ISSUE TITLE
Unable to authenticate on Blogspot account

### ISSUE THREAD

**Issue by indiwiz** [OpenLiveWriter/OpenLiveWriter#89] opened 2015-12-11 09:08 UTC
Downloaded the latest version today morning. Tried to add my blogspot account. Selected "Other Services" on the first step, entered by blog's web address and username/password on the second. Clicked next and keep getting this error... "The user name or password is incorrect". I am on Windows 8.1.

**Comment by pekiZG** [comment] 2015-12-11 09:12
@indiwiz 
Tnx for your report.
As I understand when https://github.com/OpenLiveWriter/OpenLiveWriter/issues/5 gets resolved Blogspot authentication will start working.

**Comment by martinwoodward** [comment] 2015-12-11 11:14
Should do - closing as duplicate of #63

**Closed by martinwoodward** 2015-12-11 11:14 UTC
