### ISSUE TITLE
Writer crashes on start during "Finalizing editing template configuration"

### ISSUE THREAD

**Issue by klimcio** [OpenLiveWriter/OpenLiveWriter#296] opened 2016-01-06 16:33 UTC
Hi,

I just downloaded the Open Live Writer and wanted to link it with my wordpress blog (http://blog.mariuszklimek.eu/) hosted manually at https://linuxpl.com/ and failed. Tried twice with same effect. After I give my credentials and say yes to give my template too the program crashes on "Finalizing editing template configuration".

My OS: Windows 10 Home (10.0.10586.0)

When I checked Event Logger for some clues I found out that the module that causes the exception is C:\WINDOWS\SYSTEM32\KERNELBASE.dll.

With that error I'm unable to launch OLW. Please help :-)

**Comment by ScottIsAFool** [comment] 2016-01-06 16:45
Can you post your log file, this can be found at %localappdata%\OpenLiveWriter.

I suspect this might be a dupe of #264

**Comment by gmilazzoitag** [comment] 2016-01-07 14:23
Same exact error. Yes. It's the same of https://github.com/OpenLiveWriter/OpenLiveWriter/issues/264

**Comment by klimcio** [comment] 2016-01-11 21:47
Sorry for the delay. Here you go. I believe that gmilazzoitag may be right - it can be the same issue.

[OpenLiveWriter.zip](https://github.com/OpenLiveWriter/OpenLiveWriter/files/86445/OpenLiveWriter.zip)

**Comment by klimcio** [comment] 2016-01-11 21:50
Although I just ran update.exe from said folder and then tried again. And it worked.

**Comment by gmilazzoitag** [comment] 2016-01-11 21:57
Yes. As already written in another thread a recent update fixed it.
Bye

**Closed** 2016-01-15 20:33 UTC
