### ISSUE TITLE
Synchronize Draft from Blogger

### ISSUE THREAD

**Issue by liontux** [OpenLiveWriter/OpenLiveWriter#261] opened 2015-12-30 11:05 UTC
Hello,

First of all thanks for this "rebirth" of Live Writer. 
I want to know if it's normal that OpenLiveWriter can't request the draft already existing on a Blogger account ? If it's not the case is it planned to implement this kind of functionality ?

Thanks' for your feedback

**Comment by kidjedi** [comment] 2016-01-04 19:31
upvote (not able to access online Blogger drafts; Open Live Writer only opens local drafts)
But thanks SO MUCH for keeping Live Writer alive!

**Comment by willduff** [comment] 2016-01-05 16:42
I can reproduce this issue by going to Blogger.com, starting a new post, hitting 'Save' (*not* 'Publish') and then looking at 'Recent posts' in Open Live Writer. Hopefully we can fix this! Thanks for reporting it.

**Comment by nvella** [comment] 2019-08-10 11:24
Hi there,

I've just tried reproducing this issue, and it seemed everything worked as expected. Some time has passed since this issue was posted and now, so it's possible the issue could have been fixed. I'll close this issue for now, but if you do experience any further problems please don't hesitate to reply or create a new issue. Cheers 👍

**Closed by nvella** 2019-08-10 11:24 UTC
Labels: blogger, bug, help wanted
