### ISSUE TITLE
unable to login in with blogger

### ISSUE THREAD

**Issue by jasonhorner** [OpenLiveWriter/OpenLiveWriter#28] opened 2015-12-09 18:26 UTC
Trying to access my site during setup / launch it is asking for a url, username, and password. I'm using my gmail account and password for my blogger account I'm not sure if this is the broken oauth support. Its unclear how to login (the error messages is invalid username and password but i was able to use these credentials to login in to the blogger web portal)  or even launch the program without providing the blog connection information perhaps this shouldn't be required.

**Comment by gduncan411** [comment] 2015-12-09 18:35
I have the same issue (kind of). 

In my case, I'm using 2 Factor and have created an App Password for OLW, but no matter what I try, I can't connect to Blogger with OLW.

I'm currently using WLW with Blogger (with its own App Password) and it's working fine. I've copied the working settings (URL/ID and my new OLW App Password) and no joy. "Invalid User ID or Password"

Scott's post is a little unclear as to if Blogger should work today or not (it IS clear about the future though)

**Comment by asishv** [comment] 2015-12-09 19:46
This is being working on at the moment see issue #5

**Comment by jasonhorner** [comment] 2015-12-09 19:47
outstanding... would you like me to open a separate issue for being able to launch the app without providing the services credentials

**Comment by ram7489** [comment] 2015-12-09 20:22
Wonderful—it's being worked on. :+1:

**Comment by asishv** [comment] 2015-12-09 22:30
@jasonhorner sounds similar to #35 if not open a separate issue.

**Comment by ibonobo** [comment] 2015-12-10 03:08
It's great that it's being worked on! I use WLW '12 in portable mode and have no problem logging in to Blogger with it, but cannot with OLW and could not figure out why..

**Comment by timheuer** [comment] 2015-12-11 02:15
Duplicate of #5 which should resolve this when complete.

**Closed by timheuer** 2015-12-11 02:15 UTC
