### ISSUE TITLE
Jekyll support for github pages

### ISSUE THREAD

**Issue by angshuman** [OpenLiveWriter/OpenLiveWriter#168] opened 2015-12-17 19:50 UTC
This is a much needed feature. Jekyll is not even officially supported on Windows and I think the 'Open Live Writer' product will gain a lot of traction if github pages is supported. Because of course, all the cool kids are using github. Thanks!

**Comment by martinwoodward** [comment] 2015-12-17 21:00
Agreed - take a look at #55 where some smart folks are trying to figure this out.

Closing as a duplicate of #55.

**Closed by martinwoodward** 2015-12-17 21:00 UTC

**Comment by rebornix** [comment] 2015-12-18 02:45
@angshuman we are working on GitHub Page integration and have implemented a few basic functions. You can follow https://github.com/rebornix/OpenLiveWriter/issues/1 for update.
