### ISSUE TITLE
Can't open All (more than 4-500?) articles on Blogger

### ISSUE THREAD

**Issue by ibonobo** [OpenLiveWriter/OpenLiveWriter#329] opened 2016-01-24 21:15 UTC
Trying to open "all" articles in a blog having more than 1 thousand (and, judging by the error, any blog having more than 500) results in an error.
![20160124-screenshot1](https://cloud.githubusercontent.com/assets/679170/12538938/df026f14-c2b4-11e5-9d7a-636e7f872c0e.jpg)

This is probably not a OLW error as it is a Blogger error, but I think OLW should handle it better. Here's the actual text:
> 
> The service blogger has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
> We're sorry, but the value for field max_results is larger than the maximum allowed page size of 500. [400]
> Errors [
> 	Message[We're sorry, but the value for field max_results is larger than the maximum allowed page size of 500.] Location[ - ] Reason[invalid] Domain[global]
> ]
> 
>    at Google.Apis.Requests.ClientServiceRequest`1.Execute()
>    at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetRecentPosts(String blogId, Int32 maxPosts, Boolean includeCategories, Nullable`1 now)
>    at OpenLiveWriter.BlogClient.Blog.GetRecentPosts(Int32 maxPosts, Boolean includeCategories)
>    at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPosts(RecentPostRequest request, Boolean getPages)
>    at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetRecentPosts(RecentPostRequest request)
>    at OpenLiveWriter.PostEditor.OpenPost.BlogPostListBox.GetRecentPostsAsyncOperation.DoWork()
>    at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by kathweaver** [comment] 2016-01-25 18:33
I believe this is a duplicate of #247

**Comment by willduff** [comment] 2016-02-03 16:59
Closing as dupe of #247.

**Closed by willduff** 2016-02-03 16:59 UTC
