### ISSUE TITLE
OLW and Blogger - Continuing Problems with Photos

### ISSUE THREAD

**Issue by Shoshiplatypus** [OpenLiveWriter/OpenLiveWriter#805] opened 2019-03-30 19:15 UTC
When Google+ closed, every single photo on my 8-year-old blog disappeared, and I am gradually working through the enormous task of putting them back in. I am having to use the workaround of inserting photos into my draft from Google Photos, which is very time consuming but I can put up with that if I have to until someone sorts out the problem and enables me to insert photos into my draft post from my hard drive as I used to. However, over the past few days, people are reporting that they cannot see the photos in my blog posts once they have been published. They are just getting a grey rectangle with an exclamation mark in it. When I go online, I can see them OK. What is happening, and how can I put this right?

Any news on getting OLW to work properly again since the closure of Google+ and Picasa? All I want is for this to work as it used to.

Shoshi

**Comment by Shoshiplatypus** [comment] 2019-04-03 10:25
If anyone out there is dealing with this forum I should be very, very grateful for some input on how to deal with these ongoing problems. All I am getting at present is a resounding silence.

Answers, please!!

Shoshi

**Comment by survivor303** [comment] 2019-05-04 23:08
This isnt OLW problem and btw, my blog working just like it use to after google+ went down for consumers.

Do you have doing something with the album/folder inside of a photos or google drive? they can be hidden but they need to be public, so you cannot make them private. If they are private, then blogger cannot access them for public view. If you are signed in your Google account, then you can see them because you have rights to see them as a owner. So yes i think that the problem is that OLW album is private for some reason.

**Comment by chuahtc** [comment] 2019-06-14 09:31
The URLs of the pictures uploaded to Google Photos is not permanent. The are dynamic and change after a certain time.

Read the first paragraph here:

https://developers.google.com/photos/library/guides/access-media-items

**Comment by nvella** [comment] 2019-07-06 09:32
Hi,

Blogger image upload for new posts should working again as of #810. The grey rectangle/exclamation mark seems to be a permission issue on the individual photos you've uploaded to Google Photos manually, rather than a specific issue with Open Live Writer. I'll close this issue for now, but please don't hesitate to ask any further questions.

Regards, Nick

**Closed by nvella** 2019-07-06 09:32 UTC
Labels: blogger, bug
