### ISSUE TITLE
Google Blogger scheduled post is scheduled at the wrong time

### ISSUE THREAD

**Issue by pjpontes** [OpenLiveWriter/OpenLiveWriter#224] opened 2015-12-23 03:08 UTC
Is anyone having publishing hour bug? When I schedule a post to a certain hour, it's published 3 hours later. I am at -3 GMT. I have to fix it in the blogger editor, always.

**Comment by martinwoodward** [comment] 2015-12-23 09:35
Is this against Blogger? (If it is then it is a known issue that we still need to fix I'm afraid)

**Comment by pjpontes** [comment] 2015-12-23 13:04
Yes, it happens when I schedule posts in Blogger. I work it around scheduling in OLW 3 hours before the hour I want it to be published. As I am on -3 GMT, it seems that OLW is always on 0.

**Comment by Happy4OLW** [comment] 2016-01-04 02:32
Same thing happening except that I am GMT-5 and it's schedule 5 hours later than I am requesting.  Using blogger as well.  Will attempt your workaround. Thanks.

**Comment by willduff** [comment] 2016-02-07 18:58
Closing as dupe of issue #262 - Google Blogger scheduled post is scheduled at wrong time

**Comment by willduff** [comment] 2016-02-07 22:52
Whoops, #262 is actually Wordpress related, I'll use this bug (#224) to track the Google Blogger bug.

**Comment by willduff** [comment] 2016-02-07 22:55
I have a fix for Google Blogger scheduling posts at the wrong time (pull request #358), but I'd like to get a few volunteers to test the changes. I have a version of Open Live Writer that I've built that contains the fix. Please follow these instructions and then report back if it worked or didn't work for you. Thanks!

1. Close Open Live Writer if you have it running
2. Download and run my fixed version here: https://ci.appveyor.com/api/buildjobs/731kkwc1m5aqxya9/artifacts/Releases/OpenLiveWriterSetup.exe (note: you may get a Windows Smartscreen dialog complaining that this app is unrecognized, you'll need to click **More info** > **Run anyway**)
3. Create a new post and schedule it out at a specific time in the future.
![image](https://cloud.githubusercontent.com/assets/134678/12874393/16d5bf1c-cd88-11e5-96ae-5128de602f36.png)
4. Post to Blogger
5. Go to http://www.blogger.com, login to your blog and find the post you scheduled. Is the time zone correct? Is the scheduled time as expected? In my case, I am on Pacific Standard time, so this fix worked for me.
![image](https://cloud.githubusercontent.com/assets/134678/12874411/641a9e82-cd88-11e5-9195-043d7e143bc9.png)

/cc
@robertjm @jdhitsolutions @Happy4OLW @cgroveacademy @JillEH @jtbworld @kandiphillips @DawnL43072 @survivor303 @banders03 @kathweaver @romona @pjpontes @supalm

**Comment by kathweaver** [comment] 2016-02-07 23:09
I am in Dallas (central time).  At 5:07 I told blogger I wanted it posted at 6:07 and it shows published at 4:07 pm and shows as published.

**Comment by kathweaver** [comment] 2016-02-07 23:18
By the way, the scheduled bug is in Typepad too.  I raised the issue.

**Comment by willduff** [comment] 2016-02-08 16:43
@kathweaver Can you please schedule a new post for several days away and then login to blogger.com, find the post you scheduled and tell me what time zone you see listed? In order to fix this, I need to understand what time zone you are in currently and what time zone Google Blogger is using for your account. Thanks!

**Comment by kathweaver** [comment] 2016-02-08 23:21
I scheduled a post for 2/10 at 5:18 pm, it shows that it is scheduled for 3:18 pm Pacific Time.  My time was 5:18 pm Central Time.  That seems right?

**Comment by willduff** [comment] 2016-02-10 16:32
@kathweaver Yes, that second time seems right, but your first attempt seems like it went wrong. I'm curious - is your Google Blogger blog timezone set to Pacific Time or Central Time? You can find it by going to http://www.blogger.com, find your blog overview, click **Settings** > **Language and formatting** > **Time Zone**

**Comment by kathweaver** [comment] 2016-02-10 17:34
It's set to Pacific.

**Comment by DawnL43072** [comment] 2016-02-10 18:19
I’m not kathweaver…. But with the same problem. My blogger time zone is set to Eastern, which is correct. When I schedule a post in OLW for 8am, in Blogger it is set for 1pm. 

Dawn

 

 

@kathweaver <https://github.com/kathweaver>  Yes, that second time seems right, but your first attempt seems like it went wrong. I'm curious - is your Google Blogger blog timezone set to Pacific Time or Central Time? You can find it by going to http://www.blogger.com, find your blog overview, click Settings > Language and formatting > Time Zone

**Comment by willduff** [comment] 2016-02-13 22:12
This is fixed with pull request #358.

**Closed by willduff** 2016-02-13 22:12 UTC

**Comment by DawnL43072** [comment] 2016-02-25 12:33
Which means what exactly?

**Comment by ScottIsAFool** [comment] 2016-02-25 12:35
It means it is in 0.6.0.0. Once Live Writer has updated on your computer you will have this fix.

**Comment by DawnL43072** [comment] 2016-02-25 13:56
Ah…ok, thanks! 

 

 

It means it is in 0.6.0.0. Once Live Writer has updated on your computer you will have this fix.
