### ISSUE TITLE
OLW 0.5.1.4 crashes with KERNELBASE.DLL error

### ISSUE THREAD

**Issue by gmilazzoitag** [OpenLiveWriter/OpenLiveWriter#264] opened 2015-12-30 19:06 UTC
This evening with no apparent changes in my PC with Windows 10 once opened the program after few seconds it crashes with message "OLW stopped to work".
In Event Viewer I just can see 

Name of the module generating error: KERNELBASE.dll, versione: 10.0.10586.0, timestamp: 0x5632da1c
Codice eccezione: 0x4000001f
Offset errore 0x001382e2
(...)
C:\Users\Giacomo\AppData\Local\OpenLiveWriter\app-0.5.1.4\OpenLiveWriter.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
ID segnalazione: 356602da-9d15-431f-b478-43071f087533

**Comment by kathweaver** [comment] 2015-12-30 19:24
Can you add the log file?

it's in %localappdata%\OpenLiveWriter

You can also get to it by clicking on the File Tab, Clicking on About, and at the bottom click on Show Log File. 

Thanks!

**Comment by gmilazzoitag** [comment] 2015-12-31 09:45
Here is it.
Yesterday I've removed the application and restarted the configuration. Once logged in Blogger it has started the downloading of themes and so on but once started OLW exe it crashes.
This morning seemed to work for setup asked me to publish the temporary post...but once done it it crashes starting the exe-
Event Viewer reports always the same.


[Open Live Writer.zip](https://github.com/OpenLiveWriter/OpenLiveWriter/files/75479/Open.Live.Writer.zip)

**Comment by gmilazzoitag** [comment] 2016-01-03 19:37
Here there's my same issue. Resolutions?
https://github.com/OpenLiveWriter/OpenLiveWriter/issues/267

**Comment by nvella** [comment] 2019-08-10 11:32
Closing as duplicate of closed issues #267 and #296. Seems this was possibly a regression maybe caused by a Windows update. Please don't hesitate to reply to this issue, or create a new one, if you still face problems.

**Closed by nvella** 2019-08-10 11:32 UTC
