### ISSUE TITLE
Manual save of new draft post leads to assert failure

### ISSUE THREAD

**Issue by coldacid** [OpenLiveWriter/OpenLiveWriter#330] opened 2016-01-24 22:38 UTC
I tried saving a new draft post locally and received the following assert failure message box:

    ---------------------------
    Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
    ---------------------------
    ERROR: Incorrect AppUserModelID for WindowsLiveWriter.Post.1: Windows Live Writer - {33CFF92E-5CC9-43c8-B4EE-B5501A6FC53F}
       at OpenLiveWriter.PostEditor.JumpList.JumpList.DumpFileRegistration(JumpListCustomCategory category)
       at OpenLiveWriter.PostEditor.JumpList.JumpList.AppendCustomCategories()
       at OpenLiveWriter.PostEditor.JumpList.JumpList.Refresh()
       at OpenLiveWriter.PostEditor.JumpList.WriterJumpList.Invalidate(IntPtr ownerWindow)
       at OpenLiveWriter.PostEditor.PostEditorMainControl.FirePostListChangedEvent()
       at OpenLiveWriter.PostEditor.PostEditorMainControl._editingManager_UserSavedPost(Object sender, EventArgs e)
       at OpenLiveWriter.PostEditor.BlogPostEditingManager.SaveDraft()
       at OpenLiveWriter.PostEditor.PostEditorMainControl.commandSavePost_Execute(Object sender, EventArgs e)
       at OpenLiveWriter.ApplicationFramework.Command.RaiseEvent(Object eventKey, EventArgs e)
       at OpenLiveWriter.ApplicationFramework.Command.OnExecute(EventArgs e)
       at OpenLiveWriter.ApplicationFramework.Command.PerformExecute()
       at OpenLiveWriter.ApplicationFramework.Command.PerformExecute(CommandExecutionVerb verb, PropertyKeyRef key, PropVariantRef currentValue, IUISimplePropertySet commandExecutionProperties)
       at OpenLiveWriter.ApplicationFramework.CommandManager.Execute(UInt32 commandId, CommandExecutionVerb verb, PropertyKeyRef key, PropVariantRef currentValue, IUISimplePropertySet commandExecutionProperties)
       at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.Launcher.ThreadMain(Object[] parameters)
       at OpenLiveWriter.CoreServices.Threading.ThreadStartWithParams.Run()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
    ---------------------------
    Abort   Retry   Ignore    
    ---------------------------

Ignore/continue under debugger lead to this next message:

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
System.InvalidOperationException: The file type is not registered with this application.
   at OpenLiveWriter.PostEditor.JumpList.JumpList.AppendCustomCategories()
   at OpenLiveWriter.PostEditor.JumpList.JumpList.Refresh()
   at OpenLiveWriter.PostEditor.JumpList.WriterJumpList.Invalidate(IntPtr ownerWindow)

   at OpenLiveWriter.PostEditor.JumpList.WriterJumpList.Invalidate(IntPtr ownerWindow)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.FirePostListChangedEvent()
   at OpenLiveWriter.PostEditor.PostEditorMainControl._editingManager_UserSavedPost(Object sender, EventArgs e)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.SaveDraft()
   at OpenLiveWriter.PostEditor.PostEditorMainControl.commandSavePost_Execute(Object sender, EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.RaiseEvent(Object eventKey, EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.OnExecute(EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.PerformExecute()
   at OpenLiveWriter.ApplicationFramework.Command.PerformExecute(CommandExecutionVerb verb, PropertyKeyRef key, PropVariantRef currentValue, IUISimplePropertySet commandExecutionProperties)
   at OpenLiveWriter.ApplicationFramework.CommandManager.Execute(UInt32 commandId, CommandExecutionVerb verb, PropertyKeyRef key, PropVariantRef currentValue, IUISimplePropertySet commandExecutionProperties)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at OpenLiveWriter.ApplicationFramework.SatelliteApplicationForm.Launcher.ThreadMain(Object[] parameters)
   at OpenLiveWriter.CoreServices.Threading.ThreadStartWithParams.Run()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
---------------------------
Abort   Retry   Ignore   
---------------------------
```

The post was still successfully saved.

Version 0.5.1.4, on Windows 10.

[Open Live Writer.log](https://github.com/OpenLiveWriter/OpenLiveWriter/files/102587/Open.Live.Writer.log.txt)

**Comment by ScottIsAFool** [comment] 2016-01-24 23:04
I believe this is a duplicate of #96

**Comment by coldacid** [comment] 2016-01-25 00:29
Could be.

**Comment by willduff** [comment] 2016-02-03 17:00
Closing as dupe of #96.

**Closed by willduff** 2016-02-03 17:00 UTC
