### ISSUE TITLE
Wrong post date and time

### ISSUE THREAD

**Issue by JillEH** [OpenLiveWriter/OpenLiveWriter#350] opened 2016-02-02 17:13 UTC
I have read about similar issues . . . I just started using Open Live Writer.  But when I publish a post to my blog, the date and time are always wrong.  Like if I try to post today (Feb 2, 2016) at 9pm it will post on my blog as Feb 3, 2016 at 4am.  My time zone is set correctly in Blogger.  I can't seem to find anything in Open Live Writer that will allow me to set a time zone.

On the screen for Open Live where I create my post, the date and time are shown correctly but they get posted wrong on my blog.

It seems like this happens when I am trying to do a post for a past date.  If I create a post that I plan on publishing right then, the date is usually fine.  But I have also had the date be wrong even when I am publishing with the current day/time selected.

Is this something I fix?  Or something you are working on?

Thanks!
Jill

**Comment by kathweaver** [comment] 2016-02-03 03:48
Yes, it is being worked on.  This is a duplicate of  #262 if you would like to track it.

**Closed** 2016-02-03 08:27 UTC

**Comment by JillEH** [comment] 2016-02-03 14:35
Thanks!  I will follow that line then to see what happens.
