### ISSUE TITLE
Blogger Theme not downloading

### ISSUE THREAD

**Issue by tja-dhl** [OpenLiveWriter/OpenLiveWriter#291] opened 2016-01-06 00:38 UTC
Still can't connect to Blogger or Tumblr (Tumblr is not even listed).  Thought this new open source version would have fixed these old issues.  Perhaps in the future?

**Comment by ScottIsAFool** [comment] 2016-01-06 07:51
Tumblr isn't supported. What errors are you getting with Blogger? Can you post your log file please, this can be found in %localappdata%\OpenLiveWriter

**Comment by tja-dhl** [comment] 2016-01-06 18:25
Sorry. My mistake.  Was using the wrong login info.  Got Blogger to work.  When I selected to download theme, I received the following error (see attachment).  Got it to work after three attempts, but I don't think it's using the Blogger theme.  Wordpress blog and theme working fine.  P.S. Any plans to support Tumblr in the future?  Thanks for your help....
![blogger_error](https://cloud.githubusercontent.com/assets/16567558/12150633/e68c6d60-b478-11e5-9836-10b631a98fa1.jpg)

**Comment by ScottIsAFool** [comment] 2016-01-06 19:37
For the crashing of live writer, can you please provide the log file (and maybe any log in the windows event log could be useful).

**Comment by tja-dhl** [comment] 2016-01-08 05:10
Log attached….

**Comment by ScottIsAFool** [comment] 2016-01-08 08:18
Unfortunately, if you attached it to an email reply, it won't post it to Github, you need to add it via the website.

**Comment by tja-dhl** [comment] 2016-01-08 15:55
Open Live Writer Log File....
[open_live_writer.txt](https://github.com/OpenLiveWriter/OpenLiveWriter/files/82887/open_live_writer.txt)

**Comment by ScottIsAFool** [comment] 2016-01-08 15:57
Thanks for that, closing this one now as it's a duplicate of #267

**Closed by ScottIsAFool** 2016-01-08 15:57 UTC
