### ISSUE TITLE
Saving doesn't mark categories as saved

### ISSUE THREAD

**Issue by gperrow** [OpenLiveWriter/OpenLiveWriter#190] opened 2015-12-20 05:14 UTC
If I change the categories on an article but do nothing else, saving it doesn't mark them as saved so if I try to quit OLW or open a different article, it tells me I have unsaved changes.

Repro:
1. Create an article and save it.
2. Change the categories and nothing else. Click save.
3. Without making any further changes, try to close the OLW window. You will be told you have unsaved changes and asked if you want to save them.

This happened with WLW as well.

**Comment by jannavarro** [comment] 2015-12-28 09:30
newbie on OLW code here but will try to look at this issue.

**Comment by ScottIsAFool** [comment] 2015-12-28 09:34
Might be worth checking if this is still actually an issue, it could have been fixed by #228

**Comment by jannavarro** [comment] 2015-12-28 13:02
I did a PR #252 in case #228 did not fix it.

**Comment by nvella** [comment] 2019-08-10 06:31
Confirming as fixed as could not reproduce. Closing

**Closed by nvella** 2019-08-10 06:31 UTC
Labels: bug, help wanted
