### ISSUE TITLE
Suddenly getting 501 error with photos

### ISSUE THREAD

**Issue by vacationdreamer** [OpenLiveWriter/OpenLiveWriter#564] opened 2017-02-18 12:22 UTC
I was updating my blog yesterday without a problem then suddenly it stopped responding.  I tried again this morning and when I do a text only post, it works.  When I insert photos it does not.

[](https://www.flickr.com/photos/123643618@N06/shares/6wP052url)

**Comment by vacationdreamer** [comment] 2017-02-18 12:23
https://www.flickr.com/photos/123643618@N06/shares/6wP052

**Comment by bayfieldbunch** [comment] 2017-02-18 14:24
same for us...   had to revert back to using blogger only.  hope they fine the issue soon.

**Comment by Lozula** [comment] 2017-02-19 11:54
I write my posts in OLW and then upload the photos via the blogger interface. It's a pain for sure.

**Comment by ScottIsAFool** [comment] 2017-02-19 11:55
Hi, this is an issue we're aware of and are trying to reproduce it ourselves so we can get a fix in place.

**Comment by bayfieldbunch** [comment] 2017-02-19 20:09
Thank you Scott

**Comment by bayfieldbunch** [comment] 2017-02-23 03:06
here is the error log:   OpenLiveWriter,1.3348,None,00001,15-Feb-2017 15:46:55.674,"Migrating user settings...",""
OpenLiveWriter,1.3348,None,00002,15-Feb-2017 15:46:55.674,"Starting Open Live Writer 0.6.0.0",""
OpenLiveWriter,1.3348,None,00003,15-Feb-2017 15:46:55.674,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.3348,None,00004,15-Feb-2017 15:46:55.705,"Failed to load blog settings for: ",""
OpenLiveWriter,1.3348,None,00005,15-Feb-2017 15:46:55.705,"Default blog has invalid client type, ignoring blog.",""
OpenLiveWriter,1.3348,None,00006,15-Feb-2017 15:47:17.258,"Unable to download file """" during Blog service detection: System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.Net.WebRequest.Create(String requestUriString)
   at OpenLiveWriter.CoreServices.HttpRequestHelper.CreateHttpWebRequest(String requestUri, Boolean allowAutoRedirect, Nullable`1 connectTimeoutMs, Nullable`1 readWriteTimeoutMs)
   at OpenLiveWriter.CoreServices.HttpRequestHelper.SendRequest(String requestUri, HttpRequestFilter filter)
   at OpenLiveWriter.CoreServices.HttpRequestHelper.SafeSendRequest(String requestUri, HttpRequestFilter filter)
   at OpenLiveWriter.CoreServices.HttpRequestHelper.SafeDownloadFile(String fileUrl, String& responseUri, HttpRequestFilter filter)",""
OpenLiveWriter,1.3348,None,00007,15-Feb-2017 15:47:27.681,"Failed to download template Framed: System.Exception: Unable to locate blog post elements using most recent post
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at OpenLiveWriter.BlogClient.Detection.BlogEditingTemplateDetector.ParseWebpageIntoEditingTemplate_OnUIThread(Control uiContext, BlogPostRegionLocatorStrategy regionLocator, IProgressHost progress)
   at OpenLiveWriter.BlogClient.Detection.BlogEditingTemplateDetector.GetBlogTemplateFiles(IProgressHost progress, BlogPostRegionLocatorStrategy regionLocatorStrategy, BlogEditingTemplateStrategy[] templateStrategies, BlogEditingTemplateType[] templateTypes)",""
OpenLiveWriter,1.3348,None,00008,15-Feb-2017 15:47:29.087,"Failed to download template Webpage: System.Exception: Unable to locate blog post elements using most recent post
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at OpenLiveWriter.BlogClient.Detection.BlogEditingTemplateDetector.ParseWebpageIntoEditingTemplate_OnUIThread(Control uiContext, BlogPostRegionLocatorStrategy regionLocator, IProgressHost progress)
   at OpenLiveWriter.BlogClient.Detection.BlogEditingTemplateDetector.GetBlogTemplateFiles(IProgressHost progress, BlogPostRegionLocatorStrategy regionLocatorStrategy, BlogEditingTemplateStrategy[] templateStrategies, BlogEditingTemplateType[] templateTypes)",""
OpenLiveWriter,1.3348,None,00009,15-Feb-2017 15:48:04.391,"Failed to load blog settings for: ",""
OpenLiveWriter,1.3348,None,00010,15-Feb-2017 15:48:04.391,"Default blog has invalid client type, ignoring blog.",""
OpenLiveWriter,1.3348,None,00011,15-Feb-2017 15:48:04.969,"499 499",""
OpenLiveWriter,1.3348,None,00012,15-Feb-2017 15:48:05.110,"UpdateSemanticHtmlPreviewAsyncOperation started for blog(0220b048-f42b-4495-8df5-1ad012bba3b7)",""
OpenLiveWriter,1.3348,None,00013,15-Feb-2017 15:48:05.469,"Creating a readable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00014,15-Feb-2017 15:48:05.469,"Failed to create ribbon stream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.3348,None,00015,15-Feb-2017 15:48:05.578,"Creating a readable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00016,15-Feb-2017 15:48:05.578,"Failed to create ribbon stream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat: hr = 80070002",""
OpenLiveWriter,1.3348,None,00017,15-Feb-2017 15:48:23.192,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00018,15-Feb-2017 15:48:30.505,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00019,15-Feb-2017 15:48:39.960,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00020,15-Feb-2017 15:48:45.852,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00021,15-Feb-2017 15:48:50.900,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00022,15-Feb-2017 15:48:55.245,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00023,15-Feb-2017 15:48:58.324,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00024,15-Feb-2017 15:50:32.740,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00025,15-Feb-2017 15:50:49.509,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00026,15-Feb-2017 15:50:56.041,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00027,15-Feb-2017 15:50:58.197,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00028,15-Feb-2017 15:53:21.056,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00029,15-Feb-2017 15:53:41.785,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00030,15-Feb-2017 15:53:45.882,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00031,15-Feb-2017 15:54:33.260,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00032,15-Feb-2017 15:54:35.902,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00033,15-Feb-2017 15:55:43.862,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.3348,None,00034,15-Feb-2017 15:55:51.258,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.9424,None,00001,15-Feb-2017 20:44:31.544,"Starting Open Live Writer 0.6.0.0",""
OpenLiveWriter,1.9424,None,00002,15-Feb-2017 20:44:31.544,".NET version: 4.0.30319.42000",""
OpenLiveWriter,1.9424,None,00003,15-Feb-2017 20:44:32.198,"499 499",""
OpenLiveWriter,1.9424,None,00004,15-Feb-2017 20:44:32.761,"Creating a readable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,1.9424,None,00005,15-Feb-2017 20:44:46.499,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,2.3592,None,00001,16-Feb-2017 10:43:04.568,"Starting Open Live Writer 0.6.0.0",""
OpenLiveWriter,2.3592,None,00002,16-Feb-2017 10:43:04.568,".NET version: 4.0.30319.42000",""
OpenLiveWriter,2.3592,None,00003,16-Feb-2017 10:43:05.318,"499 499",""
OpenLiveWriter,2.3592,None,00004,16-Feb-2017 10:43:06.021,"Creating a readable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,2.3592,None,00005,16-Feb-2017 10:43:18.288,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,2.3592,None,00006,16-Feb-2017 10:43:22.507,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,2.3592,None,00007,16-Feb-2017 10:53:08.798,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,8.13268,None,00001,22-Feb-2017 19:58:54.108,"Starting Open Live Writer 0.6.0.0",""
OpenLiveWriter,8.13268,None,00002,22-Feb-2017 19:58:54.108,".NET version: 4.0.30319.42000",""
OpenLiveWriter,8.13268,None,00003,22-Feb-2017 19:58:55.577,"499 499",""
OpenLiveWriter,8.13268,None,00004,22-Feb-2017 19:58:57.156,"Creating a readable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,8.13268,None,00005,22-Feb-2017 19:59:09.267,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,8.13268,None,00006,22-Feb-2017 19:59:12.251,"Creating a writable ribbon istream for C:\Users\Al\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""

**Comment by vacationdreamer** [comment] 2017-02-23 12:02
I can't thank you enough for looking into it.

**Comment by notinjersey** [comment] 2017-02-23 13:50
I'm wondering if blogger updated something in their system...this only started happening for me yesterday though, not as long ago as the first post here.

**Comment by SteveP-UK** [comment] 2017-02-23 14:03
Still working OK for me - text and photos. AFAIK mine is a standard OLW
setup

Happy to test stuff if that helps.

Regards

Steve

**Comment by jongalloway** [comment] 2017-03-09 21:48
Update:
 * We're working with the Blogger team to see if there's a way to fix this, since it looks like it was caused by a change to their photo APIs (not sure if this is possible yet)
 * We'll post an official wiki page that explains how to create the necessary directory in Google Photos and show a link to it in the error message
 * We're working on getting an updated release out soon with the fixes listed above
 * We'll be closing duplicates of this issue and pointing them to this one

**Comment by jongalloway** [comment] 2017-03-12 20:03
Closing as a duplicate of #562

**Closed by jongalloway** 2017-03-12 20:03 UTC
