### ISSUE TITLE
Failing to publish with Blogger

### ISSUE THREAD

**Issue by Jfbbb8** [OpenLiveWriter/OpenLiveWriter#842] opened 2019-07-23 02:06 UTC
It has been a while since I published to Blogger with OLW. I tried today and I am able to download my theme but when I try to publish, the publish dialog box comes up and then disappears immediate with no error message. Attached is the log file.
[OLW.log.zip](https://github.com/OpenLiveWriter/OpenLiveWriter/files/3419840/OLW.log.zip)

**Comment by nvella** [comment] 2019-07-23 15:57
Hi @Jfbbb8,

Were you attempting to post an image when this issue occurred? This could be related to the recent blogger image upload fix. Kind regards.

**Comment by Jfbbb8** [comment] 2019-07-23 17:47
The post had local pictures. What fix is this?

**Comment by nvella** [comment] 2019-07-24 02:28
A few months ago Google deprecated the Picasa API that OLW was using to post images to Blogger. They have not yet made public an API that allows posting of images in the same way that the Blogger web app does, so a workaround was developed which uploads post images to Google Drive. Google Photos was not able to be used due to API limitations with obtaining public photo URLs.

This fix is currently in the development builds, however an official release has not been made as of yet which includes the fix. You can find the installers for the development builds here; https://ci.appveyor.com/project/dotnetfoundation/openlivewriter/build/artifacts, but please keep in mind that these are development builds and may contain other unrelated bugs, such as issue #838 where the app continuously spawns new instances of itself. If you're feeling adventurous, you can try the workaround described in that issue to get the app into a stable state.

A new official release should be made soon, however I unfortunately do not have a date on when that will be. I'm currently working on a major feature which I'll be submitting a pull request for soon, however after that I plan on immediately tackling that issue #838 I mentioned above so users can use development builds without any hassle. Apologies for the inconveniences.

**Comment by Jfbbb8** [comment] 2019-07-24 03:12
Thanks so much for the help. When I try the dev release I get this
Google.Apis.Requests.RequestError
Insufficient Permission: Request had insufficient authentication scopes. [403]
Errors [
	Message[Insufficient Permission: Request had insufficient authentication scopes.] Location[ - ] Reason[insufficientPermissions] Domain[global]
]

**Comment by nvella** [comment] 2019-07-24 08:55
Hi again @Jfbbb8. Try re-adding your blog to OLW, I believe that specific error is caused by it trying to use the pre-existing authentication tokens, which aren't authorized for the Google Drive write access.

**Comment by Jfbbb8** [comment] 2019-07-24 14:44
Great, that did it. Thanks!

**Comment by nvella** [comment] 2019-07-24 15:41
Sounds good, I'll close this issue for the time being 👍 As you are running a development release now, please be sure to lodge a new issue if you run into any more problems. Cheers

**Closed by nvella** 2019-07-24 15:41 UTC
Labels: blogger, bug
