### ISSUE TITLE
Won't post 2016 post

### ISSUE THREAD

**Issue by supalm** [OpenLiveWriter/OpenLiveWriter#277] opened 2016-01-03 05:53 UTC
I tried to post my first post of 2016 and it does not show up on my blog on blogger.

**Comment by ScottIsAFool** [comment] 2016-01-03 08:10
Did you get any errors when posting? Can you attach your log file please? It's in %localappdata%\openlivewriter

**Comment by supalm** [comment] 2016-01-03 17:39
I did not get any errors. It acted like it posted in Open Live Writer. I scheduled it to post Jan 2 and nothing posted. But today Jan 3 it is  posted and said it posted Jan 3. I also notice that I scheduled the previous blog to post Dec 30  and it posted immediately on Jan 2  but says it is posted Dec 31.


I just figured out how to get open live writer to work yesterday (Jan 2) and redid all the pages from Dec 11 and on, the rest of them  posted on the day I scheduled them.


I don't know what a log file is.


Thank you so much for working on Open Live writer, I don't like the blogger software, the live writer is much easier to work with photos in. 


suep



-----Original Message-----

**Comment by ScottIsAFool** [comment] 2016-01-03 17:45
Ah ok, is your blog hosted on Blogger? If so, scheduling posts for a different time is a known issue at the moment, we're still working out a fix for that.

**Comment by supalm** [comment] 2016-01-03 18:40
Thank you getting back to me. I am assuming when the issue is resolved it will update automatically? Thanks for all your work. s



-----Original Message-----

**Comment by ScottIsAFool** [comment] 2016-01-03 18:54
It will, yes.

**Comment by willduff** [comment] 2016-01-05 17:07
Closing this as a duplicate of issue #224 - Publishing hour bug.

**Closed by willduff** 2016-01-05 17:07 UTC
