### ISSUE TITLE
How can I uninstall completely Open Source Live Writer?

### ISSUE THREAD

**Issue by 1755isla** [OpenLiveWriter/OpenLiveWriter#251] opened 2015-12-28 11:45 UTC
Yes I've uninstalled Open Source Live Writer because I'm spanyard. But now, when I go to boot my PC always appears one window with this warning: "Do you want that this program make changes in your System? Of course, I choose "Not". The question is, ¿How can I uninstall completely your application?
Thanks in advance, and Greetings for your fork.

**Comment by kathweaver** [comment] 2015-12-28 15:32
There are at least two places that you have to make changes.

1)  Delete files saved at %appdata%\local\OpenLiveWriter
2) Registry keys at HKEY_CURRENT_USER\Software\OpenLiveWriter

**Comment by 1755isla** [comment] 2015-12-28 17:36
@kathweaver:
Hello, Kathleen, from Spain.
Many thanks for your reply.
Your solution is very nice.

**Comment by kathweaver** [comment] 2015-12-28 19:43
Great!  Glad I could help.  Could you close the issue then (I can't)

**Comment by kathweaver** [comment] 2015-12-28 19:45
Duplicate of Issue #119

**Closed** 2015-12-28 20:17 UTC
