### ISSUE TITLE
Space between pictures

### ISSUE THREAD

**Issue by sboyd000** [OpenLiveWriter/OpenLiveWriter#691] opened 2017-11-23 15:20 UTC
Previously when I imported pictures into a post being created in OWL, they came in with a line or two between them into which text could be written.  I've updated to the latest OWL version and now there is no space at all.  I can select the photo after inserting it and change the margins so that the pictures are not directly beneath each other but nothing can be types into this space.   Did I inadvertently change something when I upgraded?   It's a lot of trouble to move the pictures further apart if I select two or three at a time.   thanks for the help.

**Comment by nvella** [comment] 2019-07-19 15:03
I can confirm this bug still exists, when multiple images are inserted it is hard to caption them as they all appear on the same line.

**Comment by ranjanjharavi** [comment] 2019-10-15 11:15
Hi @nvella, How should images appear then, vertically with some spaces/lines between them, or just the spaces between the images horizontally.

**Comment by nvella** [comment] 2019-10-17 06:29
Hi @ranjanjharavi, thanks for your interest in the issue!

I believe the issue is in reference to when multiple images are selected for insertion in the file picker. I'm not too quite sure if this issue was present in the original Live Writer, but either way I think it'd be a good thing to have.

![image](https://user-images.githubusercontent.com/8158648/66983149-9ba52c80-f103-11e9-9b97-a229649fac38.png)

## Current behaviour

![image](https://user-images.githubusercontent.com/8158648/66982938-0e61d800-f103-11e9-8fb3-52d945713734.png)

![image](https://user-images.githubusercontent.com/8158648/66982946-14f04f80-f103-11e9-8d67-aa1f5c0d5282.png)

## Desired

![image](https://user-images.githubusercontent.com/8158648/66982893-ebcfbf00-f102-11e9-8557-9751606e6683.png)

![image](https://user-images.githubusercontent.com/8158648/66982903-f722ea80-f102-11e9-9b8f-2a902cc2f5d1.png)

"Line below the image" text would not be automatically inserted, just the paragraph tag so text could be inserted

Cheers 😄

**Comment by ranjanjharavi** [comment] 2019-10-18 07:59
Hi @nvella,  Thank you for the clarification. 😃 
I was able to insert a line using paragraph tag so that text can be entered. Please review the PR.

**Comment by nvella** [comment] 2019-10-19 07:32
Fixed in #876

**Closed by nvella** 2019-10-19 07:32 UTC
Labels: bug, good first issue, ui-ux
