### ISSUE TITLE
Blog won't post with photo's

### ISSUE THREAD

**Issue by tubbystar** [OpenLiveWriter/OpenLiveWriter#559] opened 2017-02-09 11:52 UTC
Hi, I am currently unable to post blogs to Blogger that contain photo's. I get the following message: "The server returned an error: (501) not implemented." I am added pictures from my hard drive as per usual. As soon as the photos are removed, the blog is posted just fine. Any help would be very much appreciated. Thanks. Windows 10.

**Comment by tubbystar** [comment] 2017-02-09 12:11
Swapping to an older Google account done the trick.

**Comment by bayfieldbunch** [comment] 2017-02-12 22:26
same issue....can only publish text

**Comment by bayfieldbunch** [comment] 2017-02-14 14:28
thebayfieldbunch.com    we prefer OLW as opposed to composing with blogger.  Hope someone can figure out the issue.
Edit


thebayfieldbunch.blogspot.com
redirects

**Comment by tubbystar** [comment] 2017-02-22 14:06
It' re-occurred for me too now. ;-(

**Comment by jongalloway** [comment] 2017-03-12 20:04
Closing as a duplicate of #562

**Closed by jongalloway** 2017-03-12 20:04 UTC
