### ISSUE TITLE
Can post to blogger blog but can't download from blogger blog

### ISSUE THREAD

**Issue by toobob** [OpenLiveWriter/OpenLiveWriter#233] opened 2015-12-23 16:12 UTC
first, thank you to everyone working to save Open Live Writer. everything has been working well until, starting this morning, I can post to blogger blogs but I can not download posts from my blogger blogs to edit. 
I get the following:

![1](https://cloud.githubusercontent.com/assets/16415096/11980029/c41ff314-a965-11e5-872b-d0b545bc0c83.jpg)

ArgumentNullException

System.ArgumentNullException: Value cannot be null.
Parameter name: values
   at System.String.Join(String separator, IEnumerable`1 values)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.ConvertToBlogPost(Post post)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.<>c.<GetRecentPosts>b__38_0(Post p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OpenLiveWriter.BlogClient.Clients.GoogleBloggerv3Client.GetRecentPosts(String blogId, Int32 maxPosts, Boolean includeCategories, Nullable`1 now)
   at OpenLiveWriter.BlogClient.Blog.GetRecentPosts(Int32 maxPosts, Boolean includeCategories)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetPosts(RecentPostRequest request, Boolean getPages)
   at OpenLiveWriter.PostEditor.RemoteWeblogBlogPostSource.GetRecentPosts(RecentPostRequest request)
   at OpenLiveWriter.PostEditor.OpenPost.BlogPostListBox.GetRecentPostsAsyncOperation.DoWork()
   at OpenLiveWriter.CoreServices.AsyncOperation.InternalStart()

**Comment by martinwoodward** [comment] 2015-12-23 16:20
I suspect this is a bug in some code I added around label support (here https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs#L91)

Can you point me at the recent blog post that you are trying to edit?

**Comment by ScottIsAFool** [comment] 2015-12-23 16:21
@martinwoodward this has already been fixed, it's a dupe of #221

**Closed by ScottIsAFool** 2015-12-23 16:21 UTC
Labels: Blogger, bug
