### ISSUE TITLE
OLW won't install

### ISSUE THREAD

**Issue by romona** [OpenLiveWriter/OpenLiveWriter#145] opened 2015-12-15 19:07 UTC
I can't seem to get OLW to install. Every time I try, it comes back with a message that my username/password is incorrect. it's not wrong. Any suggestions????
Thanks, Romona

**Comment by ScottIsAFool** [comment] 2015-12-15 19:13
I assume you're trying to connect to a Blogger based blog? If so, this is a known issue and a fix is currently being worked on.

**Comment by romona** [comment] 2015-12-15 19:30
Thanks Scott
Yes, it is Blogger based blog. No worries, I'll just keep watching for
updates. The previous version of LW is still working fine, so I'll continue
on.
Thanks for your reply, Romona

mailto <romona@shaw.ca>:romona.king@gmail.com

WEBSITE:  http://www.northbrookdesigns.com

BLOG1: http://northbrookdesigns.blogspot.com

PINTEREST: http://pinterest.com/romonak/

**Comment by martinwoodward** [comment] 2015-12-15 19:58
Closing as duplicate of #63

**Closed by martinwoodward** 2015-12-15 19:58 UTC
