### ISSUE TITLE
Convert Google Blogger ClientLogin to OAuth 2.0

### ISSUE THREAD

**Issue by writeline** [OpenLiveWriter/OpenLiveWriter#5] opened 2015-12-09 11:49 UTC
Google Blogger deprecated ClientLogin in 2012 but Open Live Writer is still using it. We should update to OAuth 2.0. Google provides a .NET library for OAuth 2.0 at https://github.com/google/google-api-dotnet-client.

Following is a brief history of the current work on this issue.

We identified the code where the login process and the BloggerAtomClient, but for doing this we need to modify the UI of the wizard and create a new step where we prompt the user to click on authorization process and then get the OAuth token from Google Server. 

There are some open questions:
- Where do we store the token, as the password of the user on the CredentialStorage?
- When and how to handle OAuth invalidations, for example when the user is going to publish but he handle is invalid, ect.
- We need to create a Application inside Google Developer Console, I can create now using my personal google account but, of couse, in the future we need to use Microsoft´s account for creating this app.

Work has been done by @guerrerotook and @asishv

So the remaining items are 
- Uploading youtube videos
- Obtaining categories [@guerrerotook mentioned that this is working but I was not able to use it] 
- Adding new categories to a post
- Testing edge cases in general
- Code cleanup [I believe the wizard strings are hardcoded in the code not in strings.resx file]

@willduff, @wasker, @RobDolin, @SiTox, @Eilon

**Comment by gene7299** [comment] 2015-12-11 12:01
How about the image uploading to Google Photos?

**Comment by ericasisme** [comment] 2015-12-12 05:17
Issue #63 is a duplicate of this issue, with many users commenting that they are getting an error when trying to log into Blogger.  

Environment:  Windows 10

Steps to reproduce:
1.  Download and install OLW
2.  Connect to your blogger blog
3.  OLW not able to automatically detect settings
3a.  Select 'Blogger'
3b.  Remote pasting field is auto-populated (I do not know if this is correct, it says 
http://www.blogger.com/feeds/default/blogs
4. Get user name / password incorrect Error

**Comment by ronmartmsft** [comment] 2015-12-12 12:14
This could not have happened at a worse time given how many bloggers rely on the holiday season for income. It seems that Google has taken the release of this product as a green light to finally deprecate the legacy auth leaving Blogger users stranded.

Track here - https://productforums.google.com/forum/?utm_medium=email&utm_source=footer#!msg/blogger/lw_sNsyySKI/FyMxf1DBBwAJ

If you guys have any Google contacts, please ask them to reconsider this until after the holiday season and turn back on the legacy support.

**Comment by willduff** [comment] 2015-12-16 18:34
Good news everyone, I just finished coding initial support for Google Blogger in Open Live Writer. I have a 'nightly' build for those that are willing to try out pre-release software. Please let me know if you see any issues, other than the known ones below.

Known issues:
  * You need to remove your old Google Blogger accounts from Open Live Writer first. After removing them, click the 'Add blog account...' button in Open Live Writer to set up your Google Blogger accounts.
  * Scheduling a published post may be a few hours off.
  * Categories are no longer supported in the latest Blogger API v3.
  * Support for authors, tags and comment policies is not enabled yet.
  * Attempting to login to Google Blogger with 0 blogs will show an error message. Please create a blog on http://www.blogger.com first before using Open Live Writer.

The download link is: https://olw.blob.core.windows.net/nightly/Releases/OpenLiveWriterSetup.exe

/cc
@ronmartmsft, @gene7299

**Comment by aabelro** [comment] 2015-12-16 19:37
It works! Thank you.
The only problem that noticed was that having multiple blogs (6), OLW kept sending an access permission request to Blogger and I had to acknowledge it for every blog. It was not a real problem, just that I suppose Blogger needs to authorize OLW just one time.

**Comment by SteveP-UK** [comment] 2015-12-16 20:02
Works for me too! #OLW

**Comment by kathweaver** [comment] 2015-12-16 22:07
Works for me.  However, I only have Blogger account.  Everything appears to be working!

**Comment by willduff** [comment] 2015-12-16 22:30
@aabelro Yes, this was a tradeoff I made for simplicity in the case where a user only has one blog. It's something we could look into making more effortless in the future though, thank you for the feedback.

@SteveP-UK and @kathweaver - Thank you for testing!

**Comment by ericasisme** [comment] 2015-12-17 04:47
It seems to be working!  Thank you so much!  I just put words and pictures
and publish.
The other night I didn't make it as far as the interface.  It's great that
the GUI is exactly the same as the last version of WLW.  A lot of times
Open Source stuff I've seen looks really different, and glad to see this
pick up where WLW left off!
The only thing that was a little weird was I was already logged into Google
in Chrome, but it asked me to log into the new e with Windows 10 (I forget
the name) and give OLW permission.  It was no big deal and it connected
just fine, I just mention it in case it's not the expected behavior.

**Comment by ronaero1** [comment] 2015-12-17 07:04
Receiving the following error while trying to access "Local Drafts" or "Open recent Posts"! Any subjestions?

 Thursday, December 17, 2015 12:53:34 AM

Version: 0.5.1.2

OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Runtime version: 4.0.30319.34209
Shutdown started: False
Program: "C:\Users\Main\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.exe" --squirrel-firstrun

Memory Load: 50%
Total Physical: 8063 MB
Available Physical: 3967 MB
Total Page File: 8561 MB
Available Page File: 4167 MB
Total Virtual: 2047 MB
Available Virtual: 1604 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.


OpenLiveWriter.PostEditor.PostEditorStorageException: Error Accessing Local Post - Unexpected error occurred while accessing local post (UnauthorizedAccessException)

Access to the path 'C:\Users\Main\AppData\Local\Temp\OpenLiveWriter1257078411\supfilesE0326AB\SpellingContext' is denied.
   at OpenLiveWriter.PostEditor.PostEditorFile.Load(Boolean addToRecentDocs)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.OpenLocalPost(PostInfo postInfo)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.OpenLiveWriter.PostEditor.IBlogPostEditingSite.OpenLocalPost(PostInfo postInfo)
   at OpenLiveWriter.PostEditor.Commands.DraftPostItemsGalleryCommand.DraftPostItemsGalleryCommand_Execute(Object sender, EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.RaiseEvent(Object eventKey, EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.OnExecute(EventArgs e)

**Comment by martinwoodward** [comment] 2015-12-17 08:59
@ericasisme - if Edge is your default browser (which it is by default on Windows 10) then the behavior you describe is expected. Great to hear that you are up and running

**Comment by martinwoodward** [comment] 2015-12-17 09:03
@ronaero1 - I think you are running into issue #26. Still need a fix for that one.

**Comment by StephenCWLL** [comment] 2015-12-17 10:34
Sorry, I'm a bit late as wasn't near a compuyer yesterday!

Just installed it (I uninstalled previous version first).

Not published or edited anything yet. I'm all signed in thanks with blogger, so that's much better :)

Couple of installation notes:

Edge reports downloading your exe as "Unsafe". Didn't take screenshot :( But think it's due to the same reason as next note below. Edge is my default browser.
Smartscreen pops up a blue warning message that the application is unrecognised and giving you the choice to run or not run it. Think this is because there's no publisher information for the exe.
![ss](https://cloud.githubusercontent.com/assets/16239355/11867530/9f7766f2-a4a9-11e5-8558-c1dd09bb7dd1.JPG)
The Edge window that popped up for Google Blogger Authentication didn't close automatically afterwards. Edge is my default browser.
Also noticed it won't open my recent post (which I think I did open last in WLW) with the same error as that chap for before. i.e. the Edge issue.

More later when I get to play with it :) Thanks for your work thus far.

**Comment by romona** [comment] 2015-12-17 14:16
Thank you Will and everyone who made OLW work with Blogger. It's really appreciated. I created a test blog and did some customizing on the page, uploaded a test post etc. The only thing I've found so far that I can't change, is the font in the title of the post. It's defaults to Arial. The font box greys out and will only allow that one font. Other than that, so far, all seems well. Will continue to use the original one for a while yet to see what else might change in the open source version. But thanks again, so glad this is now working... Romona

**Comment by StephenCWLL** [comment] 2015-12-17 15:36
Just written a blog purely from OLW, went to publish it, and I get this:

The remote server returned an error: (403) Forbidden.

It won't even upload a draft atm. It was earlier when I was playing about.

**Comment by ScottIsAFool** [comment] 2015-12-17 15:42
@StephenCWLL Can you try the workaround in this blog post please? http://www.madrasnow.com/2015/12/solved-open-live-writer-login-issue.html

**Comment by StephenCWLL** [comment] 2015-12-17 15:46
Ha! Yeah, I'd just done that before I was coming back here to say I'd fixed it :) Thanks though. That did the trick. Great minds think alike ;O)

**Comment by willduff** [comment] 2015-12-17 16:55
Hey @StephenCWLL, I'd be interested to see your log file to investigate the (403) Forbidden error. Can you launch Open Live Writer, then go to *File* | *About* | *Show log file* and email the log file to mailto:openlivewriter-team@dotnetfoundation.org? Thanks!

**Comment by willduff** [comment] 2015-12-17 17:05
Actually, I was able to repro the (403) Forbidden error myself. Seems to be a re-authorization issue, I'll look into it.

**Comment by willduff** [comment] 2015-12-17 17:05
Fixed with pull request #101.

**Closed by willduff** 2015-12-17 17:05 UTC
Labels: Blogger

**Comment by StephenCWLL** [comment] 2015-12-17 17:07
@willduff Dude, I didn't even have time to read your message :p Ok, I'll leave you to it then :)

**Comment by way0utwest** [comment] 2015-12-24 16:42
First, thank you all for the work done here. Once again, I can write offline and publish to multiple Blogger blogs from OLW. I very much appreciate your efforts.

Second, Merry Christmas and Happy Holidays. You've given me a great gift with your efforts here and I hope you enjoy your holidays.

**Comment by ericasisme** [comment] 2015-12-30 03:53
I just got that error tonight.  What is the fix?

**Comment by kathweaver** [comment] 2015-12-30 04:04
Do you have the latest version of OpenLiveWriter?  You can check by looking at File About page.  We're at Build 0.5.1.4
