### ISSUE TITLE
OpenLiveWriter.exe has stopped working

### ISSUE THREAD

**Issue by 1pluschh** [OpenLiveWriter/OpenLiveWriter#270] opened 2016-01-01 15:52 UTC
First, thank you to those of you who are making OLW possible!

I got a new computer and am transferring things over.  Installed OLW yesterday {12/31}, got blogs all set up, everything worked fine for a few hours.  Then tried to load and it will not load! 

Have tried - uninstalling and reintalling, restarted computer several times

Computer is Lenovo Yoga 900, running Windows 10.  I am not sure what I have done to cause this since it was working fine. The only thing I can remember doing in between it working and it not working is adding the My Weblogs folder to this new computer -- then I tried to open OLW to see if the drafts were there and OLW wouldn't open.  

Thanks for any help!

**Comment by ScottIsAFool** [comment] 2016-01-01 16:04
Can you please post your log file. It's in %localappdata%\OpenLiveWriter.

**Comment by 1pluschh** [comment] 2016-01-01 16:25
I think this is it, sorry if it's not.  I also saved a text file called "Squirrel Set Up" when I tried to reinstall and it wouldn't install.

OpenLiveWriter,3.10668,None,00001,01-Jan-2016 10:48:30.444,"Starting Open Live Writer 0.5.1.4",""
OpenLiveWriter,3.10668,None,00002,01-Jan-2016 10:48:30.445,".NET version: 4.0.30319.42000",""
OpenLiveWriter,3.10668,None,00003,01-Jan-2016 10:48:30.810,"499 499",""
OpenLiveWriter,3.10668,None,00004,01-Jan-2016 10:48:30.888,"UpdateSemanticHtmlPreviewAsyncOperation started for blog(96280c28-a7ba-4fca-9bc3-37f8d6bb3629)",""
OpenLiveWriter,3.10668,None,00005,01-Jan-2016 10:48:31.134,"Creating a readable ribbon istream for C:\Users\Carisa\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,3.10668,None,00006,01-Jan-2016 10:48:35.886,"Creating a writable ribbon istream for C:\Users\Carisa\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""
OpenLiveWriter,3.5460,None,00001,01-Jan-2016 10:55:19.833,"Starting Open Live Writer 0.5.1.4",""
OpenLiveWriter,3.5460,None,00002,01-Jan-2016 10:55:19.833,".NET version: 4.0.30319.42000",""
OpenLiveWriter,3.5460,None,00003,01-Jan-2016 10:55:20.177,"499 499",""
OpenLiveWriter,3.5460,None,00004,01-Jan-2016 10:55:20.240,"UpdateSemanticHtmlPreviewAsyncOperation started for blog(96280c28-a7ba-4fca-9bc3-37f8d6bb3629)",""
OpenLiveWriter,3.5460,None,00005,01-Jan-2016 10:55:20.479,"Creating a readable ribbon istream for C:\Users\Carisa\AppData\Roaming\OpenLiveWriter\Ribbon.dat",""

**Comment by 1pluschh** [comment] 2016-01-01 20:11
I have double checked on my old computer an it is working fine there, which is of course driving me nuts. My old computer is running Windows 7 and also has regular Live Writer installed and I am able to use both over there, no problems. 

I can't get either to load here, I tried to install Live Writer here just to check and it give me the same error. 

Let me know if you need that set up text log, it has tons in it -- I tried to read it and got all confused. 

Thanks again for any help, I really appreciate it.

**Comment by 1pluschh** [comment] 2016-01-01 23:44
Update - I went into appdata and deleted all files associated with OLW and LW and did a reinstall of OLW and it worked. When I went in to update my blog's theme OLW crashed but I was able to reopen it.

Main problem now -- it isn't pulling in my theme properly -- it's tiny {I have wordpress and blogger blogs - both are like that}.  I am guessing this may have something to do with screen resolution? My screen resolution on this computer is 3200x1800 -- does that have anything to do with it?  I published a post and it looks fine on the actual blog but in OLW it is super tiny I can barely see what I am doing even when I ctrl/scroll to enlarge.

**Comment by ScottIsAFool** [comment] 2016-01-02 08:11
If it's crashing when getting the theme, I suspect it might be the same as #267 (if it's your blogger blog it's doing it on). Can you post the log file which will confirm.

**Comment by gmilazzoitag** [comment] 2016-01-03 19:38
Same issue or a quite similar one. See https://github.com/OpenLiveWriter/OpenLiveWriter/issues/267

**Comment by willduff** [comment] 2016-01-05 17:01
Closing as a duplicate of issue #267.

The issue of your font being tiny is a duplicate of issue #202.

**Closed by willduff** 2016-01-05 17:01 UTC
