### ISSUE TITLE
time difference

### ISSUE THREAD

**Issue by cgroveacademy** [OpenLiveWriter/OpenLiveWriter#305] opened 2016-01-11 15:03 UTC
When I schedule posts onto blogger through OLW the time I schedule and the time they read as scheduled in Blogger are different... how do I fix that?  Thanks!

**Comment by ScottIsAFool** [comment] 2016-01-11 15:05
Hi, thanks for reporting this. It's actually a known issue right now that we're looking to address. Closing this as a duplicate of #224

**Closed by ScottIsAFool** 2016-01-11 15:05 UTC
