### ISSUE TITLE
Saved Drafts/Posts In WLW Won't Work in OLW

### ISSUE THREAD

**Issue by Indy27** [OpenLiveWriter/OpenLiveWriter#152] opened 2015-12-17 00:52 UTC
I try to open up a saved post using OLW only to get unexpected error. Is anyone one having this same problem? The error info is down below:

Version: 0.5.1.2

OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Runtime version: 4.0.30319.42000
Shutdown started: False
Program: "C:\Users\***\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.exe" --squirrel-firstrun

Memory Load: 83%
Total Physical: 14318 MB
Available Physical: 2375 MB
Total Page File: 29828 MB
Available Page File: 5968 MB
Total Virtual: 2047 MB
Available Virtual: 1703 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.

OpenLiveWriter.PostEditor.PostEditorStorageException: Error Accessing Local Post - Unexpected error occurred while accessing local post (UnauthorizedAccessException)

Access to the path 'C:\Users\***\AppData\Local\Temp\OpenLiveWriter1401189033\supfiles2266DD96\SpellingContext' is denied.
   at OpenLiveWriter.PostEditor.PostEditorFile.Load(Boolean addToRecentDocs)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.OpenLocalPost(PostInfo postInfo)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.OpenLiveWriter.PostEditor.IBlogPostEditingSite.OpenLocalPost(PostInfo postInfo)
   at OpenLiveWriter.PostEditor.Commands.RecentItemsCommand.RecentItemsCommand_ExecuteWithArgs(Object sender, ExecuteEventHandlerArgs args)
   at OpenLiveWriter.ApplicationFramework.Command.RaiseEvent(Object eventKey, ExecuteEventHandlerArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.OnExecute(ExecuteEventHandlerArgs args)

**Comment by ScottIsAFool** [comment] 2015-12-17 00:56
Yep, I saw this too, earlier.

**Comment by Indy27** [comment] 2015-12-17 02:26
Does it also have to do with why there's not a category feature for
Blogger* (works on every other platform)

* Not related to the issue I posted earlier, but is important nontheless.

**Comment by TheHorrorClub** [comment] 2015-12-17 03:36
Getting the same thing as Indy27 above. OLW is up and working fine, I'm able to post from OLW, but cannot access any local drafts from my Blogger Blog.

**Comment by ScottIsAFool** [comment] 2015-12-17 09:03
@Indy27 I don't believe it's related to anything to do with Blogger, I got it for my wordpress blog

**Comment by ScottIsAFool** [comment] 2015-12-17 09:12
Looks like this is a Dupe of #26. Please follow that bug for any further updates on this issue.

**Closed by ScottIsAFool** 2015-12-17 09:12 UTC
Labels: bug, help wanted
