### ISSUE TITLE
Won't accept password

### ISSUE THREAD

**Issue by JoniWebb** [OpenLiveWriter/OpenLiveWriter#125] opened 2015-12-14 08:48 UTC
I've been on Live Writer for almost 9 years and right now, after doing this all day, I swear, If I had a gun I would put it through my head.  I am crying. Thank God for whoever has finally done this!  A huge thank you!  I will pay if I can get it to work.  ok Today, Live Writer wouldn't connect to my blog. Changed passwords, reinstalled Live Writer which was a fiasco, nothing works.  Found you - installed OLW -but it still won't accept my password - so I can't get a screen to write on - here or on LW.  Someone take mercy on me and help me.  Please.  I'm desperate.  I can't use Blogger to write.  Please help me!!!!

**Comment by pekiZG** [comment] 2015-12-14 08:58
Hi @JoniWebb 

I'm guessing you are trying to login to Google Blogger.
This is currently being worked on as you can see here https://github.com/OpenLiveWriter/OpenLiveWriter/issues/5

**Comment by JoniWebb** [comment] 2015-12-14 09:04
I see now. What a horrible day.  Let me ask you this - is there anyway to at least get the OLW to open so that I can type on it and then copy paste it to Blogger?  All I get is the rejected authentication screen due to bad password.Thanks a million!

**Comment by pekiZG** [comment] 2015-12-14 09:10
Well,

from the top of my head i would say install VS2015 and run it from there.
I know there is a feature req. to allow installation without configuring blog account.
https://github.com/OpenLiveWriter/OpenLiveWriter/issues/35

There is a workaround there. If it's not clear, you can ask for help there.

Hope that helped

**Comment by JoniWebb** [comment] 2015-12-14 09:39
Sorry to bug you but what is VS2015 and where could I find it? Thanks!

**Comment by JoniWebb** [comment] 2015-12-14 09:43
oh - Visual Studio.  ok.  got it.  So - there is no way to get to the blank page to write on - on OWL without inputing the blogger address/password?  No way around that?

**Comment by JoniWebb** [comment] 2015-12-14 09:46
And one more think, I just took out my older computer and tried blogger/LW on it - and same thing.  It won't accept the password.  So, it def. is not my computer.  I was hoping!

**Comment by ScottIsAFool** [comment] 2015-12-14 11:02
No, this issue sadly affects OLW and WLW, but a fix is in progress and near (we're hoping this week).

**Comment by Shoshiplatypus** [comment] 2015-12-14 15:24
Thank you for this. I am experiencing exactly the same problem. I am reassured to hear that the fix is in progress and that we can expect some news soon! I am getting desperate not being able to post to my blogger blog. Thank you for your hard work on our behalf, whoever is doing this.

Shoshi

**Comment by martinwoodward** [comment] 2015-12-14 16:07
Closing as a duplicate of #63 - stay tuned, update on progress for Blogger soon.

**Closed** 2015-12-14 16:07 UTC
