### ISSUE TITLE
Fix PostEditorStorageException in OpenLiveWriter.PostEditor.PostEditorFile.Load

### ISSUE THREAD

**Issue by martinwoodward** [OpenLiveWriter/OpenLiveWriter#293] opened 2016-01-06 07:23 UTC
### Stacktrace (first of multiple) ###

<pre>OpenLiveWriter.PostEditor.PostEditorFile;Load;;
OpenLiveWriter.PostEditor.BlogPostEditingManager;OpenLocalPost;;
OpenLiveWriter.PostEditor.PostEditorMainControl.OpenLiveWriter.PostEditor.IBlogPostEditingSite;OpenLocalPost;;
OpenLiveWriter.PostEditor.Commands.DraftPostItemsGalleryCommand;DraftPostItemsGalleryCommand_Execute;;
OpenLiveWriter.ApplicationFramework.Command;RaiseEvent;;
OpenLiveWriter.ApplicationFramework.Command;OnExecute;;</pre>

### Reason ###

OpenLiveWriter.PostEditor.PostEditorStorageException: Error Accessing Local Post - Unexpected error occurred while accessing local post (UnauthorizedAccessException)

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/249213/crash_reasons/74853294](https://rink.hockeyapp.net/manage/apps/249213/crash_reasons/74853294)

**Comment by willduff** [comment] 2016-01-15 20:30
This is a duplicate of #26 - OLW won't open local drafts or published posts, throws an UnauthorizedAccessException. We fixed that and pushed out a new version already.

**Closed by willduff** 2016-01-15 20:30 UTC
Labels: bug, high-priority
