### ISSUE TITLE
arghhhhh!

### ISSUE THREAD

**Issue by GlennDL** [OpenLiveWriter/OpenLiveWriter#129] opened 2015-12-14 16:02 UTC
Am I in the right place? WLW stopped working, I downloaded OLW but couldn't get signed in (user name or password incorrect), created account in GetHub and have been searching for a solution., but I'm not a developer and this appears to be technical discussions about code, and more code. Is there a right place, a forum THAT SPEAKS ENGLISH, and hopefully tells me what to do now, not in the future?

**Comment by timheuer** [comment] 2015-12-14 16:04
Are you on Blogger/Blogspot?

**Comment by GlennDL** [comment] 2015-12-14 16:07
Yes

**Comment by ScottIsAFool** [comment] 2015-12-14 16:09
A fix is being worked on for this issue. In the meantime, if you still have WLW installed, the only real suggestion I can make is to still write your post in Live Writer, then copy the post's html into the blogger post editor online. Not ideal, I know, but best I can come up with.

**Comment by martinwoodward** [comment] 2015-12-14 16:11
Closing a duplicate of #63 for now. Stay tuned - folks are working on a fix.

**Closed by martinwoodward** 2015-12-14 16:11 UTC

**Comment by GlennDL** [comment] 2015-12-14 16:12
Thank you, tried that with the dissater back in May/June... is there a thread, post, or site that I can link to for when the solution is posted?

**Comment by pekiZG** [comment] 2015-12-14 16:13
I'm just guessing it will be here :)
http://openlivewriter.org/

**Comment by ScottIsAFool** [comment] 2015-12-14 16:14
The issue in question is #5 and an easy way to keep up to date would be to subscribe to the mailing list.
