### ISSUE TITLE
Unhandled exception dialog if google OAuth fails

### ISSUE THREAD

**Issue by Wintermute21** [OpenLiveWriter/OpenLiveWriter#619] opened 2017-05-24 00:47 UTC
So, I'm using Windows 10 and I tried to sign in with Google Blogger.
If the OAuth fails for some reason or you click cancel, you get an unhandled exception dialog.

**Comment by ScottIsAFool** [comment] 2017-05-24 08:45
Hi, I'm unable to reproduce this. When I click on cancel in the wizard at the sign in button stage, it just cancels the wizard with no issues. Are you able to post a screenshot of the error at all please?

**Comment by ScottIsAFool** [comment] 2017-05-24 08:46
Also, are you able to confirm which version you are running please (go to File > About Open Live Writer)

**Comment by Wintermute21** [comment] 2017-05-24 09:01
Hi, this is version 0.6.2.
I'm having an issue reproducing it now myself. I'll post a screenshot as soon as I can.

**Comment by Wintermute21** [comment] 2017-05-25 20:07
@ScottIsAFool I unfortunately can no longer reproduce this either. How should I proceed?

**Comment by ScottIsAFool** [comment] 2017-05-25 21:23
I'll close the issue for now, if you have it happen again, reopen this and include a screenshot of the error and if you, can any log files https://github.com/OpenLiveWriter/OpenLiveWriter/wiki/Instructions-for-sending-your-Writer-log-file

**Closed by ScottIsAFool** 2017-05-25 21:23 UTC
