### ISSUE TITLE
Google Blogger credentials not being accepted

### ISSUE THREAD

**Issue by geeksrik** [OpenLiveWriter/OpenLiveWriter#67] opened 2015-12-10 09:08 UTC
Hello, google blogger credentials are not being accepted while setting up a blog. is it because google is not yet supported? Please let me know how i can setup a Blogger blog.

**Comment by JetzeMellema** [comment] 2015-12-10 09:42
Duplicate with #63

**Comment by martinwoodward** [comment] 2015-12-10 10:41
Yeah - sorry. This is definitely being worked on. Closing as a dupe of #63

**Closed by martinwoodward** 2015-12-10 10:41 UTC
