### ISSUE TITLE
Dead on arrival

### ISSUE THREAD

**Issue by kuemmet** [OpenLiveWriter/OpenLiveWriter#124] opened 2015-12-14 05:31 UTC
Installed too quick, like it didn't install, went straight to the sign in /  set  up screen, would not accept User name and or password.  
??
Upon opening the installer, first screen ..
![image](https://cloud.githubusercontent.com/assets/16284140/11773603/7a0373ec-a1e9-11e5-9eef-fecea6cd884b.png)
 Second screen ....
![image](https://cloud.githubusercontent.com/assets/16284140/11773619/aa71f5f8-a1e9-11e5-95c2-aa5e4bde18f0.png)

I enter my info
![image](https://cloud.githubusercontent.com/assets/16284140/11773641/de3b777e-a1e9-11e5-9bd7-ef6f10df4406.png)

Then after entering my log in information ..
This is as far as I get .. done.
![image](https://cloud.githubusercontent.com/assets/16284140/11773652/f38acf30-a1e9-11e5-80e4-59643851594e.png)

**Comment by timheuer** [comment] 2015-12-14 05:33
@kuemmet are you trying to connect to a Blogger/Blogspot site?

**Comment by kuemmet** [comment] 2015-12-14 05:47
Yes

**Comment by kuemmet** [comment] 2015-12-14 05:48
They haven't updated yet, have they?

**Comment by agoosa** [comment] 2015-12-14 05:54
I'm having the same problem, exact same actually. It won't connect to Blogger.

**Comment by kuemmet** [comment] 2015-12-14 06:01
good to know I am not the only one, this started when I tried to post 
with the old Writer about 10:30 pm, mountain time.

On 12/13/2015 10:54 PM, agoosa wrote:
>
> I'm having the same problem, exact same actually. It won't connect to 
> Blogger.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/124#issuecomment-164348436>.
>

--

**Comment by kathweaver** [comment] 2015-12-14 06:04
This is a duplicate of #5 so it can be closed.  The issue is being worked on, Blogger changed their code about the time that OpenWriter was released.

**Comment by timheuer** [comment] 2015-12-14 06:07
Closing as a dupe of #5 which is being worked on.

**Closed by timheuer** 2015-12-14 06:07 UTC

**Comment by kuemmet** [comment] 2015-12-14 06:10
Roger that ..


On 12/13/2015 11:05 PM, Kathleen Weaver wrote:
>
> This is a duplicate of #5 
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/5> so it can 
> be closed. The issue is being worked on, Blogger changed their code 
> about the time that OpenWriter was released.
>
> —will
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/124#issuecomment-164350396>.
>

--

**Comment by kuemmet** [comment] 2015-12-14 06:11
Same as # 5 , closing this one
