### ISSUE TITLE
Install Fails 

### ISSUE THREAD

**Issue by julianfrank** [OpenLiveWriter/OpenLiveWriter#309] opened 2016-01-13 15:34 UTC
Installation fails with a box saying "Open setup logs"...but on clicking 'ok' nothing happens!

I love the older Live writer...The blog feature in word (including 2013) is too heavy for me...Would be great if you could make this useable....

I'm on Win 8.1 x64 btw...

**Comment by nvella** [comment] 2019-08-17 01:51
Closing this issue as seems to be duplicate of #307 - possibly related to file permissions on the user's system.

**Closed by nvella** 2019-08-17 01:51 UTC
Labels: installer, todo-check-reproduction
