### ISSUE TITLE
Draft Retrieve from blogger

### ISSUE THREAD

**Issue by WallpapersWithQuotes** [OpenLiveWriter/OpenLiveWriter#161] opened 2015-12-17 14:57 UTC
Aslam-o-Alaikum;
When i try to retrieve a draft from blogger to writer i can't see drafts only published posts are visible.The labels from blogger  are missing in writer.
Hope both issues fixed soon.

**Comment by nvella** [comment] 2019-08-07 05:28
I couldn't reproduce this issue so I'll close it for now. Steps I took;

1. Create a draft through the Blogger web interface.
2. 'Open recent posts' in Open Live Writer and selecting my blog from the side pane.
3. I could see and load the draft I created in the post list.

**Closed by nvella** 2019-08-07 05:28 UTC
