### ISSUE TITLE
Blog Issue

### ISSUE THREAD

**Issue by rontfox** [OpenLiveWriter/OpenLiveWriter#801] opened 2019-03-22 21:19 UTC
I can no longer transfer photos from Live Writer to my blog dashboard.  I now get an error message. I've had no problems in the past.

**Comment by CCOSTAN** [comment] 2019-04-05 20:10
Seems to be Duplicate of issue #786

**Comment by nvella** [comment] 2019-07-06 09:39
Closing as a duplicate of #786 and fixed in #810. Please don't hesitate to get in touch if you have any further issues.

Regards, Nick.

**Closed by nvella** 2019-07-06 09:39 UTC
Labels: duplicate
