### ISSUE TITLE
Formatting buttons fail with some blogs

### ISSUE THREAD

**Issue by BrianMinister** [OpenLiveWriter/OpenLiveWriter#237] opened 2015-12-23 23:13 UTC
This image shows what happens when I connect to one of my WordPress blogs. When I connect to another one of them, it works fine.

So this looks like a simple bind did not have a contingency for nulls or data change. My host is WordPress.com

![htmlstyleserror](https://cloud.githubusercontent.com/assets/4028832/11986696/6f6dd0a8-a987-11e5-8c9f-a93d2478c0ba.png)

**Comment by martinwoodward** [comment] 2015-12-24 10:46
Thanks - I think it's just related to your hi-dpi display and the font styles available in your theme rather than the blog itself. Closing as a duplicate of #44

**Closed by martinwoodward** 2015-12-24 10:46 UTC
