### ISSUE TITLE
HDPI Issues

### ISSUE THREAD

**Issue by OneCyrus** [OpenLiveWriter/OpenLiveWriter#274] opened 2016-01-02 21:31 UTC
there are a few issues with HDPI. e.g. the HTML styles preview (heading, ...) displays only scrollbars on my surface pro 3. Other than that it doesn't look so bad. The content area doesn't scale as well (as far as I can tell) but it's not too bad.

![image](https://cloud.githubusercontent.com/assets/7747800/12076169/ed791a96-b19f-11e5-8aed-5ff592d3d28c.png)

**Comment by ScottIsAFool** [comment] 2016-01-02 21:53
Thanks for reporting this. Closing as it's a dupe of #44.

**Closed by ScottIsAFool** 2016-01-02 21:53 UTC
