### ISSUE TITLE
Draft file folder name and location for OLW?

### ISSUE THREAD

**Issue by ezbiker** [OpenLiveWriter/OpenLiveWriter#175] opened 2015-12-18 14:04 UTC
Hello, I have a bunch of drafts from Windows Live Writer, that I'll be posting soon to my blog. But I can't access that folder (Screen shot 218 - folder for WLW) in OLW. When you open that folder there are 2 file folders in it as you see in Screen shot 219. 
Does OLW have a similar file setup and where would I find that; so I can move my drafts into, so I can use them later? 

Thanks!  Ken aka EZ Biker www.ezbiker.com
![screenshott218](https://cloud.githubusercontent.com/assets/16262330/11898519/42bcf004-a566-11e5-8d5c-4a3af85ea149.png)
![screenshott219](https://cloud.githubusercontent.com/assets/16262330/11898520/44a1ec08-a566-11e5-8d88-8987dcbda772.png)

**Comment by ScottIsAFool** [comment] 2015-12-18 14:05
When you say you can't access it, what are you seeing? Any errors? OLW uses the same folders as WLW did so you should be able to access them just fine.

**Comment by ezbiker** [comment] 2015-12-18 14:12
I can access drafts I made today. But when I try and pull up a draft that
was made in WLW I get the following error box.
[image: Inline image 2]

Note: The drafts I just made today and past drafts are in the same folder.

On Fri, Dec 18, 2015 at 9:06 AM, Scott Lovegrove <notifications@github.com>
wrote:

> When you say you can't access it, what are you seeing? Any errors? OLW
> uses the same folders as WLW did so you should be able to access them just
> fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenLiveWriter/OpenLiveWriter/issues/175#issuecomment-165785293>
> .
>

Friday, December 18, 2015 9:08:53 AM

Version: 0.5.1.2

OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
Runtime version: 4.0.30319.34209
Shutdown started: False
Program: "C:\Users\Ken\AppData\Local\OpenLiveWriter\app-0.5.1.2\OpenLiveWriter.exe" 

Memory Load: 38%
Total Physical: 8072 MB
Available Physical: 4932 MB
Total Page File: 16143 MB
Available Page File: 12912 MB
Total Virtual: 2047 MB
Available Virtual: 1612 MB
Available Extented Virtual: 0 MB

Unexpected Error Occurred
An unexpected error has occurred within the application.


OpenLiveWriter.PostEditor.PostEditorStorageException: Error Accessing Local Post - Unexpected error occurred while accessing local post (UnauthorizedAccessException)

Access to the path 'C:\Users\Ken\AppData\Local\Temp\OpenLiveWriter-1878221629\supfiles365541\SpellingContext' is denied.
   at OpenLiveWriter.PostEditor.PostEditorFile.Load(Boolean addToRecentDocs)
   at OpenLiveWriter.PostEditor.BlogPostEditingManager.OpenLocalPost(PostInfo postInfo)
   at OpenLiveWriter.PostEditor.PostEditorMainControl.OpenLiveWriter.PostEditor.IBlogPostEditingSite.OpenLocalPost(PostInfo postInfo)
   at OpenLiveWriter.PostEditor.Commands.DraftPostItemsGalleryCommand.DraftPostItemsGalleryCommand_Execute(Object sender, EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.RaiseEvent(Object eventKey, EventArgs e)
   at OpenLiveWriter.ApplicationFramework.Command.OnExecute(EventArgs e)

**Comment by ScottIsAFool** [comment] 2015-12-18 14:14
@ezbiker ok, thanks, that's what I thought. This is currently being investigated. This is a dupe of #26.

**Closed by ScottIsAFool** 2015-12-18 14:14 UTC

**Comment by ezbiker** [comment] 2015-12-18 14:15
OK, so it's NOT me... ;-D Thanks! And thanks for the quick response.
Please cancel my submitted one?

**Comment by ScottIsAFool** [comment] 2015-12-18 14:16
It's already closed :)
