### ISSUE TITLE
Is anyone working on Open Live Writer any longer?

### ISSUE THREAD

**Issue by banders03** [OpenLiveWriter/OpenLiveWriter#787] opened 2019-01-17 00:14 UTC
Or has it been abandoned? I'm getting the 404 error message again after months of working flawlessly. I've tried all the fixes that have been suggested--updated version, created new Google photos album, recreated my account in LW all to no avail. 

Hello? Is this thing on??

**Comment by Warren9999** [comment] 2019-01-17 09:37
I have same question, is it still supported? 
The 400 error message is back thus making it impossible to post photos.
Are there any alternatives to OLW that can be suggested?

**Comment by banders03** [comment] 2019-01-17 14:04
I looked around last night for alternatives and found nothing.

**Comment by JimGalasyn** [comment] 2019-01-17 20:58
Re @banders03's question, the last significant commit was on 30 Nov 2017: https://github.com/OpenLiveWriter/OpenLiveWriter/commit/74a39a18a16a7a556c77f5c647af296b6397a208. Not a good sign. :(

**Comment by Warren9999** [comment] 2019-01-18 02:18
> What am I doing to get around this error for now.
> First I make the whole post issue in OLW. Then I upload the photos inserted in the direct post (final format) to the Google Photos Open Live Writer album.
> Lastly, I replaced the local photos in the OLW with them, but using the address of the photo obtained directly from Google Photos.
> So I can use the advantages of editing OLW. That done, just publish.
> Last time was the way I solved it last year. A while later, the error stopped and I continued to use OLW without problems

Can you clarify how you are replacing the local photos using the address of the photo from Google Photos?
Using the insert picture from web option I get message "preview is unavailable, check picture URL or network connection"
I presume there another method to do this?
Thanks in advance.

**Comment by JimGalasyn** [comment] 2019-01-18 03:11
I opened the post in OLW's *Source* tab, and replaced every instance of
"$imageXX.png" with the (very very long) URL from photos.google.com. You
need to keep track of which "$image" corresponds with which image on
photos.google.com, which is a PITA.

This should work for you, but it has the downside that the very very long
URL will cause Facebook (and possibly other) sharing to choke.

Jim

[image: photo]
*Jim Galasyn*
Technical Writer, Confluent

206-459-9058 | jim.galasyn@confluent.io

https://docs.confluent.io
<http://www.facebook.com/james.galasyn>
<http://www.linkedin.com/in/jim-galasyn/> <http://twitter.com/JimGalasyn>
Create your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own>

**Comment by crpaiva** [comment] 2019-01-18 12:53
If it were possible, I'd attach a movie to show you.
First you edit your post usually in OLW, including the photos in the final
format you want. I use PhotoShop to reduce the images at the height and
width in pixels I desire. I keep all those edited images in a specific
folder, so it's easy to upload to Google Photos.
Once the post is concluded, I get all the edited images in the final format
and upload them to Google Photos, into the OLW album, which already exists
there.
After that, I've replaced each photo in the OLW editor with its full
address (that huge link) in Google Photos, using the "Insert Picture from
the WEB" option.
You will need to redo some alignments or placements, but then just post
that will be all right.
[ ]´s
Carlos Roberto e Gleidys
www.nasestradasdoplaneta.com.br
www.cozinhapraticanasestradas.com.br
www.turislogia.com.br



Em sex, 18 de jan de 2019 às 00:18, Warren9999 <notifications@github.com>
escreveu:

**Comment by Warren9999** [comment] 2019-01-18 13:08
I uploaded my photos to Imgur photo hosting post processed and full size then used the insert photo from web. I could then resize the image as I normally would do within OLW. 

With the photo in the OLW writer window active (clicked on) I then went to the link to button (in the format tab of OLW) and set that to web address and copy and pasted the direct photo link URL shown in Imgur (second box) to the address field. I also ticked open in new window.

The result is all the photos are displayed same custom size as I would usually have them shown and when clicking on the photos they display in a window with the film strip of thumbnails below. Previously I had them display full screen in new window but this I am unable to replicate so far with this work around.

**Comment by banders03** [comment] 2019-01-18 14:15
Thanks for the steps. I have done it EXACTLY this same way and still get the error. The Google Photos album says it's shared, just like all the old ones do, so that means it's public, right? I even set up GitHub as a host and tried the same steps. Still get the error. I've deleted my account in OLW and set it up again. And again. I can sometimes publish with one photo and some text but every time I add another photo it produces the error message. This is crazy.

**Comment by LocalJoost** [comment] 2019-01-18 14:21
What is happening is very simple. Just fire up Fiddler and you will see what's wrong.
![image](https://user-images.githubusercontent.com/4129183/51392160-7e234200-1b34-11e9-8195-cd91c931464b.png)
If you analyze the error:
"The Picasa API is deprecated. See https://developers.google.com/picasa-web/ for more details and the migration guide."

Open Live Writer apparently uses an API that no longer works. I have resorted to uploading my pictures elsewhere and then referring to them via picture/on the web. It LOOKS like that does not work, but it does. You might have to close and open OLV and re-open it to actually see the picture in preview, but that's what I am using now

**Comment by JimGalasyn** [comment] 2019-01-18 16:08
@LocalJoost, good find!  Looks like some lucky person will need to rewrite the image-posting logic in [GoogleBloggerv3Client.cs](https://github.com/OpenLiveWriter/OpenLiveWriter/blob/master/src/managed/OpenLiveWriter.BlogClient/Clients/GoogleBloggerv3Client.cs).

**Comment by JimGalasyn** [comment] 2019-01-18 16:11
K everybody, I've pinged the project owner, [Rob Dolin](https://twitter.com/robdolin), on Twitter, and I've posted on the "official" [Gitter](https://gitter.im/OpenLiveWriter/OpenLiveWriter) channel. Feel free to add your voices!

**Comment by banders03** [comment] 2019-01-18 16:34
> 
> 
> > Thanks for the steps. I have done it EXACTLY this same way and still get the error. The Google Photos album says it's shared, just like all the old ones do, so that means it's public, right? I even set up GitHub as a host and tried the same steps. Still get the error. I've deleted my account in OLW and set it up again. And again. I can sometimes publish with one photo and some text but every time I add another photo it produces the error message. This is crazy.
> 
> @banders03, you need to get the URL of the image from photos.google.com (click the image to select it in the viewer, right-click the image and select "Copy image location"), then open the Source tab in OLW and replace "$imageXX.png" with the URL. If you have more than one image in the post, you have to keep track of which one goes where, which is annoying.

Thanks, I actually DID try that but it's possible I might have confused some of the images. I will try it again.

**Comment by JimGalasyn** [comment] 2019-01-18 16:35
I cloned the repo and built the solution, but it crashed. The problem is that the Tistory provider is "invalid" for some reason -- `BlogClientManager.IsValidClientType(clientType)` in the `BlogProviderFromXml` class says no to Tistory.

So I removed it from 
`OpenLiveWriter\src\managed\OpenLiveWriter.BlogClient\Providers\BlogProvidersB5.xml`, and now I can debug OLW in VS.

**Comment by banders03** [comment] 2019-01-18 16:36
> 
> 
> K everybody, I've pinged the project owner, [Rob Dolin](https://twitter.com/robdolin), on Twitter, and I've posted on the "official" [Gitter](https://gitter.im/OpenLiveWriter/OpenLiveWriter) channel. Feel free to add your voices!

Thanks for reaching out to them!! I had no idea where to reach ;-) Hopefully someone will see it and try to fix it.

**Comment by JimGalasyn** [comment] 2019-01-18 16:40
Yeah, I found that [Gitter link](https://gitter.im/OpenLiveWriter/OpenLiveWriter) buried in the [GSoC page](http://openlivewriter.org/GSoC/) on the OLW site.

**Comment by CCOSTAN** [comment] 2019-01-18 16:56
@JimGalasyn - The last commit to this repo was in December 2017.  Maybe you can reach out to some of the people that have issued pull requests that weren't merged and gather some developer support to help you on your new Fork.  If you are able to get a working solution, we (Bloggers that use OLW) can post some blog posts to help get the word out for a new maintained Repo.

**Comment by JimGalasyn** [comment] 2019-01-18 17:24
@CCOSTAN, good suggestion.

@martingbrown, @dariuszparys, @demortes , @ScottIsAFool, @manggsoft, @hashhar, what say you? You've all submitted PRs to OLW should we fork?

**Comment by demortes** [comment] 2019-01-18 17:34
I would rather see this repo maintained if the project owner wants to pass on the torch so to speak. But I have no say in how it works I think. I don't see myself contributing further either way.

**Comment by jongalloway** [comment] 2019-01-18 17:45
Duplicate of #786

**Closed by jongalloway** 2019-01-18 17:45 UTC

**Comment by jongalloway** [comment] 2019-01-18 17:56
To be clear, not trying to stifle any discussion here, just marking the issue as a dupe since we're tracking the problem under #786.

We've had some work going lately to update for .NET Core 3, but will probably need to get a hotfix out to *temporarily* work around issues with Google APIs.

**Comment by banders03** [comment] 2019-01-18 17:58
> 
> 
> To be clear, not trying to stifle any discussion here, just marking the issue as a dupe since we're tracking the problem under #786. But you can of course continue any discussion here if you'd like.
> 
> We've had some work going lately to update for .NET Core 3, but will probably need to get a hotfix out to _temporarily_ work around issues with Google APIs.

Thank you for helping us out!

**Comment by JimGalasyn** [comment] 2019-01-18 18:02
@jongalloway Thank you, Jon!

**Comment by crpaiva** [comment] 2019-01-18 18:50
I'll make a movie and will give the link for you

Em sex, 18 de jan de 2019 14:34, banders03 <notifications@github.com
escreveu:
