### ISSUE TITLE
HTML Styles - It shows a grey bar in the middle

### ISSUE THREAD

**Issue by Siriox** [OpenLiveWriter/OpenLiveWriter#116] opened 2015-12-13 04:35 UTC
Hi guys! I just installed OLW, by the way thanks for made it possible.
As appear in the image it shows a strange grey bar or block in the HTML Styles section. This is the first time I use the program.
![strange](https://cloud.githubusercontent.com/assets/16273545/11765516/c54eb2ec-a128-11e5-9028-612d604e3ad8.png)

**Comment by pekiZG** [comment] 2015-12-13 11:34
hi @Siriox thx for reporting this.
It's the same as https://github.com/OpenLiveWriter/OpenLiveWriter/issues/44

You can see progress there :)

**Comment by martinwoodward** [comment] 2015-12-13 13:38
Closing as duplicate of #44 - thanks folks

**Closed by martinwoodward** 2015-12-13 13:38 UTC
