### ISSUE TITLE
Cursor location is not preserved

### ISSUE THREAD

**Issue by mxa0079** [OpenLiveWriter/OpenLiveWriter#439] opened 2016-04-06 01:32 UTC
I am connecting to WordPress. Trying to place the cursor in the middle of the document using the mouse will not work, the cursor is always pushed to the end of the current document, making it harder to go back and edit previous sections of the blog.

Work around: use keyboard to move location to the desired location.

**Comment by ScottIsAFool** [comment] 2016-04-06 06:49
Thanks for reporting this, I believe this is a duplicate of #126

**Closed by ScottIsAFool** 2016-04-06 06:49 UTC
