### ISSUE TITLE
ERROR400

### ISSUE THREAD

**Issue by kityq00** [OpenLiveWriter/OpenLiveWriter#793] opened 2019-01-21 05:09 UTC
![51302721-27533500-1a6e-11e9-8307-dd2f41ddf7a1](https://user-images.githubusercontent.com/25845632/51454070-caad8e00-1d7d-11e9-8a5b-e1be9a48de09.png)

**Comment by gep13** [comment] 2019-01-21 07:13
@kityq00 this is a known issue which is being tracked here:

https://github.com/OpenLiveWriter/OpenLiveWriter/issues/786

It doesn't need another issue to be opened.  @jongalloway I would suggest that this be closed.

**Comment by jongalloway** [comment] 2019-01-21 08:48
Duplicate of #786

**Closed by jongalloway** 2019-01-21 08:48 UTC
