### ISSUE TITLE
OpenLiveWriter photo upload (403) Forbidden error

### ISSUE THREAD

**Issue by CatAVL** [OpenLiveWriter/OpenLiveWriter#732] opened 2018-04-06 02:52 UTC
I have been using LiveWriter for years (way before it was "Open").  I recently purchased a new computer to take with me when I travel, specifically to use with OLW for my travel blog.  I use blogspot.com as my host and had no problems interfacing between OLW and blogspot for month. Suddenly I began receiving the following error when trying to post photos on the blog:  The remote server returned an error: (403) Forbidden.
I have tried everything to correct this. Moving photos from USB storage drives to the hard drive, using full size photos instead of reduced, smaller photos, I've even tried to uninstall OLW and reinstall, but the registry obviously doesn't clear, because OLW loads in seconds and doesn't correct the issue.  I can copy and paste from web photos - but the beauty of the OLW program is that I can blog offline, then upload when I have appropriate internet access.
Has anyone had these issues?  And has anyone found a solution to the 403 error issue?  Appreciate any help you can provide.
Thanks!

**Comment by he1p** [comment] 2018-04-25 21:18
I have the same problem.  A few years ago, I had the same issue; it was only resolved when I switched from LiveWriter to OpenWriter.  I love this program for uploading to blogger.  It is much easier to manipulate pictures and text.  I need it fixed.  Anyone?

**Comment by nvella** [comment] 2019-07-07 02:58
Closing as seems to be a duplicate of #786, and is fixed in PR #810. Blogger photos now upload to Google Drive as Picasa upload has been deprecated by Google, fix should be making it's way out in the next release.

**Closed by nvella** 2019-07-07 02:58 UTC
